### ISSUE TITLE
Gnu document license does not fit in section structure

### ISSUE THREAD

**Issue by fmherschel** [SUSE/suse-best-practices#10]
Currently the GDL beginns with
"0. Preamble" but should be
"13.0" or "13.1" "Preamble"

The reason might be that the GDL is included without setting a section-indentation.
Or is that "0. Preamble" printed by plan? 
If I look at the sources I see:

[float]
== 0. PREAMBLE

**Comment by chabowski** [comment]
Hi Fabian, this is indeed by purpose - all documents have the GFDL in this format.

**Comment by petersatsuse** [comment]
On 06.11.18 13:56, Meike Chabowski wrote:
> Hi Fabian, this is indeed by purpose - all documents have the GFDL in 
> this format.

Then it needs to be always the last chapter as it would be confusing to
have e.g. 1,2,3,0,4,5

cu
  Peter

**Comment by chabowski** [comment]
Yep that is correct. The GFDL should always be the last "section" or chapter of a document.

The structure of this section is given by the Free Software Foundation. In our official SUSE product documentation, the GFDL section can have a section number in the table of contents (e.g. 8. GNU Free Documentation License) or an Appendix attribute (e.g. C. GNU Free Documentation License), but inside the section, it always has the structure starting with 0. for the Preambel etc ...). 

With regard to our SUSE Best Practices, the section number of the GFDL is listed in the table of content (this is a prerequisite to make it visible there),  but NOT on the actual page where the GDFL starts. In an SBP document, the GDFL also always starts on a separate page to clearly demonstrate this is a very specific, kind of "lone-standing" section.

Hope I could explain it well enough.

**Comment by fmherschel** [comment]
Ah! So the "0. Preamble" is something like a 1:1 quotation of the original text which should never been changed even not by a typesetting program.
In this case could close the issue.

**Comment by chabowski** [comment]
Yes indeed that is the case. Thanks! Closing issue.
