### ISSUE TITLE
[doc] Example&nbsp;28:  Main SAP HANA Update procedure, delete maintenance meta attribute

### ISSUE THREAD

**Issue by blauerdaemon** [SUSE/suse-best-practices#115]
Example&nbsp;28:  Main SAP HANA Update procedure :

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#id-1.12.4.4.5

As a last step, remove the maintenance meta attribute with:

crm resource meta master-slave-resource delete maintenance

**Comment by fmherschel** [comment]
You point is not "end" the maintenance using the crm resource maintenance <resource> off but deleting the meta attribute, so it falls back to the default and could not interference with cluster global attributes?

**Comment by fmherschel** [comment]
To be honest I would like the crm resource <res> maintenance command would be handle to do that properly instead doing a work-around at an other level.

**Comment by blauerdaemon** [comment]
I fully agree with that. But right now we need to advise customers to delete any remaining meta attributes (e.g. for manage/maintenance) each time they finish maintenance operations.  

Having the above snipped in our docs would help to prevent unfortunate cluster operations that are caused by meta attributes which are a left over from previous operations.

**Comment by fmherschel** [comment]
@blauerdaemon  Could you tell us about urgency and importance (from your point of view)?

**Comment by lpinne** [comment]
added an hint to the setup guide
