### ISSUE TITLE
[doc] 4.2  Installing ASCS on valuga11

### ISSUE THREAD

**Issue by ldevulder** [SUSE/suse-best-practices#117]
4.2  Installing ASCS on valuga11:

https://documentation.suse.com/sbp/all/html/SAP_S4HA10_SetupGuide-SLE15/index.html#_installing_ascs_on_valuga11

Like in `4.3 Installing ERS on valuga12`, the permissions on `/usr/sap/EN2/ASCS00` need to be adjust during installation, like this:
```
If you get an error during the installation about permissions, change the ownership of the ASCS directory

# chown -R en2adm:sapsys /usr/sap/EN2/ASCS00
```

**Comment by fmherschel** [comment]
Thanks for the feedback. I added this to the ASCS inst procedure.

**Comment by fmherschel** [comment]
Patch will be included in the next update.
