### ISSUE TITLE
[doc] 4.4.4  Adapting SAP Profiles to Match the SAP S/4-HA-CLU 1.0 Certification

### ISSUE THREAD

**Issue by ldevulder** [SUSE/suse-best-practices#118]
4.4.4  Adapting SAP Profiles to Match the SAP S/4-HA-CLU 1.0 Certification:

https://documentation.suse.com/sbp/all/html/SAP_S4HA10_SetupGuide-SLE15/index.html#_adapting_sap_profiles_to_match_the_sap_s4_ha_clu_1_0_certification

There are two errors in the filenames:
- `/usr/sap/EN2/SYS/profile/EN2ASCS00_sapen2as_` should be `/usr/sap/EN2/SYS/profile/EN2_ASCS00_sapen2as`
- `/usr/sap/EN2/SYS/profile/EN2ERS10_sapen2er_` should be `/usr/sap/EN2/SYS/profile/EN2_ERS10_sapen2er`

**Comment by fmherschel** [comment]
Thanks for your feedback. I will check that. I think this is a format problem (as in ADOC the underscore is also formatting bold).

**Comment by fmherschel** [comment]
The undersore marks italic (cursive) not bold. Unfortunately some times ADOC struggles, if you have undersores in the string which should be italic. This I changes now the format to bold to get rid of the bad file-name (trailing undersore).
