### ISSUE TITLE
Page break and smaller font in ADOC?

### ISSUE THREAD

**Issue by chabowski** [SUSE/suse-best-practices#12]
@fmherschel: Do you know how to insert a page break in an adoc document? The usual  <<<  does not work ...  I would like to have the GFDL separated from the rest of the document, starting on an extra page, and also with a smaller font. But all I tried did not work out. It is just cosmetics, but still would be nice to have to be "in synch" with the other SUSE Best Practices written in DocBookXML. 

See f.e.: https://www.suse.com/documentation/suse-best-practices/pdfdoc/suse-best-practices-sap-hana-on-kvm-sles-for-sap-12-sp2/suse-best-practices-sap-hana-on-kvm-sles-for-sap-12-sp2.pdf
ToC section 10

**Comment by chabowski** [comment]
@fmherschel: hmmmm - let me think about it and discuss with Frank when he is back from Prague. Thanks for the proposal however!!

**Comment by fmherschel** [comment]
@chabowski: Alternatively we could try to repair the book style and switch-back to the book-style.

**Comment by chabowski** [comment]
@fmherschel: not closing the issue, as reminder for doc team to work on a solution. However, for now, we leave the GPDL in adoc as is (normal font, no page break). After we found a viable solution, we can easily update the document. Thanks!

**Comment by chabowski** [comment]
@fmherschel 

we found a solution for the page break when processing adoc with DAPS and our style sheets. You can "fool" the system with passing an xml /xstl pdf page break at least: 

++++
<?pdfpagebreak?>
++++

There is no solution so far for the font size. The team does not support putting the GFDL into an image. Thus we leave it as is for now in the adoc documents, GFDL with normal font size.

I will close the issue now. Thanks!
