### ISSUE TITLE
[doc] Example&nbsp;1:  Installing additional software for the HA cluster 

### ISSUE THREAD

**Issue by wtmpx** [SUSE/suse-best-practices#122]
Example&nbsp;1:  Installing additional software for the HA cluster :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-1.6.5.4.3

Please let us tell customer to install this package as well supportutils-plugin-ha-sap for all SAP HANA documentation

**Comment by fmherschel** [comment]
> Please let us tell customer to install this package

Which package are you referring to? 

> as well supportutils-plugin-ha-sap 

Do you mean this one? Then I misunderstood your grammar.

**Comment by wtmpx** [comment]
Hi Fabian, 

Yes this package will collect HANA releated logs which is needed for us in support. 

# zypper if supportutils-plugin-ha-sap
Refreshing service 'SMT-http_dolly_hwlab_suse_de'.
Loading repository data...
Reading installed packages...


Information for package supportutils-plugin-ha-sap:
---------------------------------------------------
Repository     : SLE-Module-SAP-Applications15-SP1-Updates
Name           : supportutils-plugin-ha-sap
Version        : 0.0.1+git.1586941845.6e2fc42-1.3.1
Arch           : noarch
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3
Installed Size : 7.6 KiB
Installed      : Yes
Status         : up-to-date
Source package : supportutils-plugin-ha-sap-0.0.1+git.1586941845.6e2fc42-1.3.1.src
Summary        : Supportconfig Plugin for SAP and HA
Description    : 
    Extends supportconfig functionality to include system information for
    SAP and HA cluster. The supportconfig saves the related logs.

**Comment by fmherschel** [comment]
@wtmpx : How urgent/important is that?

**Comment by wtmpx** [comment]
> @wtmpx : How urgent/important is that?

Not urgent

**Comment by lpinne** [comment]
Hi wtmpx,

1. The request for supportutil-plugin-ha-sap https://bugzilla.suse.com/show_bug.cgi?id=1170085 is still in status "new."
Might be changed to solved?

2. I have created https://bugzilla.suse.com/show_bug.cgi?id=1180531 to get the RPM into pattern sap_hana and/or
sap_nw. You might look at that.

3. I have made me a note on adding the package to the next setutp guide update.
Since several guides are affected, it might take a while.

Regards,
Lars

**Comment by lpinne** [comment]
Hi,

next SAP HANA SR 15 Cost Opt guide will mention the package.


Regards,
Lars

**Comment by lpinne** [comment]
Hi,

next SAP HANA SR 15 Perf Opt guide will mention the package.

Regards,
Lars

**Comment by lpinne** [comment]
done
