### ISSUE TITLE
[doc] 4.2  Installing ASCS on valuga11

### ISSUE THREAD

**Issue by ldevulder** [SUSE/suse-best-practices#125]
4.2  Installing ASCS on valuga11:
https://documentation.suse.com/sbp/all/html/SAP_S4HA10_SetupGuide-SLE15/index.html#_installing_ascs_on_valuga11

and 
4.3 Installing ERS on valuga12:
https://documentation.suse.com/sbp/all/html/SAP_S4HA10_SetupGuide-SLE15/index.html#_installing_ers_on_valuga12

Like the database installation, I think that `clean-up` should be set to yes: `Clean-up: select Yes, remove operating system users from the group sapinst`.

**Comment by fmherschel** [comment]
No, why? This also very SAP software specific. So it depends on the decision, if the SAP Basis admin like to keep the users and goups.
Maybe they even need to install more components.

**Comment by ldevulder** [comment]
> No, why?

I asked this because it's in the [Installing Database on valuga01](https://documentation.suse.com/sbp/all/html/SAP_S4HA10_SetupGuide-SLE15/index.html#_installing_database_on_valuga01) section.

**Comment by fmherschel** [comment]
We could remove it on both. However database is something different.
The concrete decision always depends on what the SAP BASIS likes to do we (SUSE) do not need to document it. We only have the installation procedure like a short reference (for non productive installations we say how we did install it). We are not the authority to tell 100% what an SAP BASIS admin must do at SAP side. We have the authority to tell him what to do in the
SAP area.
Removing the <sid>adm group binding could have negative impacts, if the SAP BASIS admin would install more SAP instances on the same system (e.g. when the previous group number would change).

**Comment by ldevulder** [comment]
> We could remove it on both. However database is something different.
> Removing the adm group binding could have negative impacts, if the SAP BASIS admin would install more SAP instances on the same system (e.g. when the previous group number would change).

Ok, understood, thanks for the comment!
But as other instance have to be installed on `valuga01` (in the examples), it might be a good idea to remove it as well in this specific case, no?

**Comment by fmherschel** [comment]
Our SAP procedure is still only a remark. We just documented how we did install it as we processed the certfication.
