### ISSUE TITLE
[doc] 8.2.3  Cluster Configuration for All Other Cluster Nodes

### ISSUE THREAD

**Issue by rjmayne** [SUSE/suse-best-practices#133]
8.2.3  Cluster Configuration for All Other Cluster Nodes:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-12/#_cluster_configuration_for_all_other_cluster_nodes

Current text is: "Than all needed configuration files are copied over."

The word "Than" should be "Then", e.g. "Then all needed configuration files are copied over."

**Comment by fmherschel** [comment]
Fixed in sources.
