### ISSUE TITLE
[doc] 8.2.4  Check the Cluster for the First Time

### ISSUE THREAD

**Issue by rjmayne** [SUSE/suse-best-practices#134]
8.2.4  Check the Cluster for the First Time:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-12/#_check_the_cluster_for_the_first_time

The paragraph "The command will show the "empty" cluster and will print something like the screen output below. The most interesting information in this output is that there are two nodes in the status "online" and the message "partition with quorum"." refers to "two nodes in the status online", there are 7 nodes in the status online in the code shown below.

**Comment by fmherschel** [comment]
Thanks for sharing - this is most likely a copy-over from Scale-Up. I will mark this for the next update.
Fixed in sources, closing here.
