### ISSUE TITLE
[doc] Table&nbsp;3:  Description of important Resource Agent parameters 

### ISSUE THREAD

**Issue by lpinne** [SUSE/suse-best-practices#141]
Table&nbsp;3:  Description of important Resource Agent parameters :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15_AWS/index.html#id-1.10.7.9.5

**Comment by lpinne** [comment]
" If the time difference is less than the time gap, than the cluster hold ..." should be
" If the time difference is less than the time gap, then the cluster hold ..."

**Comment by chabowski** [comment]
This is fixed - as we rebuild the repo anyways, I took the chance to fix the typo. Changes will be online after the build is done.
