### ISSUE TITLE
[doc] 9.2.1  Cluster Bootstrap and More

### ISSUE THREAD

**Issue by roseswe** [SUSE/suse-best-practices#148]
9.2.1  Cluster Bootstrap and More:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#_cluster_bootstrap_and_more

The SBD is formatted with

Timeout (watchdog) : 20
Timeout (allocate) : 2
Timeout (loop)     : 1
Timeout (msgwait)  : 40 

So 
stonith-timeout="150s"

should be 48s, right?

**Comment by chabowski** [comment]
@fmherschel would you mind checking the above question? Thanks very much!

**Comment by chabowski** [comment]
> @fmherschel would you mind checking the above question? Thanks very much!

Hi @fmherschel @pirat013 @lpinne - as you are the named authors, could one of you please have a look at the comment and reply? Thank you very much!

**Comment by lpinne** [comment]
@chabowski
1. For the given sbd settings, 48s would be right.
2. The given sbd settings are known to be too short for many cases. Thus in the end resulting stonith-timeout will be in the range of 100s-150s in real life. See e.g. Azure docu.

**Comment by chabowski** [comment]
@lpinne @fmherschel do we need to do anything here now/change the document, or should I close this issue? 
Thank you!

**Comment by lpinne** [comment]
I think we can close this now
