### ISSUE TITLE
[doc] 2.1  Kubernetes Distribution -> just RKE2 and NOT RKE?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-best-practices#150]
2.1  Kubernetes Distribution:

https://documentation.suse.com/sbp/all/single-html/SBP-Private-Registry/#_kubernetes_distribution

-------------------

Any idea why we do not list RKE?

**Comment by chabowski** [comment]
@bbobrov @jsuchome @dirkmueller can you please have a look at the question above and respond? Thanks very much!

**Comment by jsuchome** [comment]
It's likely it works on different other k8s distributions, but we listed only those we explicitly tested.

**Comment by Martin-Weiss** [comment]
Any idea why we tested RKE2 and not RKE which is the standard underneath Rancher ATM?

**Comment by chabowski** [comment]
@jsuchome would you mind having a look at the question from Martin? 
I would just like to know if we need to define a follow-up action, or if we can close the issue.
Thank you very much!

**Comment by jsuchome** [comment]
I do not exactly remember, it's possible we assumed RKE2 is becoming default soon so it's better to test with something that users are expected to have.

But I'm not sure now. I suggest to close the issue. The project was killed anyway, wasn't it?

**Comment by chabowski** [comment]
Thanks @jsuchome - I will close the issue!
