### ISSUE TITLE
Feature: Separate doc page for Legal Notice and GNU Free Documentation License

### ISSUE THREAD

**Issue by jamesongithub** [SUSE/suse-best-practices#166]
For `html` and `single-html` it would be nice to be able to link to a separate page for the legal notice and the gnu license content instead of having a "compile time" include. They are pretty long and take up a lot of space on the doc. e.g. https://documentation.suse.com/sbp/all/html/SBP-SLES12SP1-SAP-migrationguide/index.html -> roughly 75% of the doc is the legal notice and gnu license, whereas the actual content is only about 25% of the page. For `pdf` you may or may not want the full content included.

**Comment by chabowski** [comment]
@sknorr would you mind having a look? Thank you!

**Comment by sknorr** [comment]
The GFDL needs to be delivered with the document, so I see no good way around this.
However, I think it would make more to relicense to a CC license, as they are more modern and do not need to be shipped as part of the document. I'd suggest a moderately permissive option like CC-Attribution-ShareAlike 4.0 International, or even a more permissive license like CC-Attribution 4.0 International.

Since most of the content comes from within the company and SUSE should be the copyright holder of all internal content (ianal), getting permission from the authors to relicense should be pro-forma only (again, ianal).

**Comment by jamesongithub** [comment]
Hi @sknorr. Thanks. We don't have to change the license right now. Do you have a pointer to where it mentions the GDFL needs to "shipped" with the doc? And what does "shipped" mean when delivered over html?

**Comment by sknorr** [comment]
You obviously found the GFDL within our documents already...

> 4. MODIFICATIONS
> You may copy and distribute a Modified Version of the Document under the conditions of sections 2 and 3 above, provided that you release the Modified Version under precisely this License, with the Modified Version filling the role of the Document, thus licensing distribution and modification of the Modified Version to whoever possesses a copy of it. In addition, you must do these things in the Modified Version:
> [...]
> - Include an unaltered copy of this License.

& 

> 6. COLLECTIONS OF DOCUMENTS
> You may make a collection consisting of the Document and other documents released under this License, and replace the individual copies of this License in the various documents with a single copy that is included in the collection, provided that you follow the rules of this License for verbatim copying of each of the documents in all other respects.
> You may extract a single document from such a collection, and distribute it individually under this License, provided you insert a copy of this License into the extracted document, and follow this License in all other respects regarding verbatim copying of that document.

* What exactly it means that the license has to be "included" with the document is something I'd have to guess--again, ianal.
* One of the issues here is that we are also building downloadable Zip archives of all SBP and we currently don't have the technical means to add extra license documents in addition to the PDFs/Single-HTMLs. Meaning, we can't make proper use of (6.) currently.

Feel free to get an actual legal professional to look at this situation. From my standpoint though, switching to a CC-BY license on a document-by-document basis seems like the easier and more future-proof solution.

**Comment by chabowski** [comment]
Thanks @sknorr and @jamesongithub. For now I will close this issue, as it is a matter of license.
