### ISSUE TITLE
GCC10 paper: Sentence seems to be wrong

### ISSUE THREAD

**Issue by chabowski** [SUSE/suse-best-practices#169]
Hi @jamborm 
would you mind having a quick look at the following senctence:

https://github.com/SUSE/suse-best-practices/blob/003f5d1a8a74f72c6d47a5bc395a67b1efce4780/xml/MAIN-SBP-GCC-10.xml#L747

Should it be 

"Optimized compilers frequently make decisions according to which path through the code they consider most likely to be executed, how many times a loop is expected to iterate, and similar estimates." 

or 

"Optimizing compilers frequently makes decisions according to which path through the code they consider most likely to be executed, how many times a loop is expected to iterate, and similar estimates." 

or something similar? The current sentence seems wrong to me.

Thanks!

**Comment by jamborm** [comment]
I think the sentence is correct as it is, it really should be "Optimizing" compilers - as in the compilers which perform optimizations (transformations to make the result run faster).

It is an established term, as or example in: https://www.amazon.com/Building-Optimizing-Compiler-Bob-Morgan-ebook/dp/B008COCE9G

The statement is about all of them, so the subject is plural and so the correct form of the verb is "make."

Basically, they often need to guess what the important parts are and prioritize them over the - guessed - less important parts, the tradeoff is often inevitable.  But I see that the sentence is quite convoluted, perhaps it can be replaced with something like the following?

  "Optimizing compilers frequently need to estimate which path through the code they is most likely to be executed, how many times a loop is expected to iterate, and similar properties."

Is that more easy to understand?

Thanks,

Martin

**Comment by chabowski** [comment]
@jamborm Yep - thank you very much for clarification- that helps. I am well aware that compiler language and terms are quite different ;-) - but that sentence really made me struggle. But I understand it now - and leave it as is, thanks again!
