### ISSUE TITLE
Clarifiy sentences in suse-best-practices/xml/MAIN-SBP-AMD-EPYC-3-SLES15SP2.xml

### ISSUE THREAD

**Issue by chabowski** [SUSE/suse-best-practices#175]
https://github.com/SUSE/suse-best-practices/blob/c08df5286843d5ffe67a7ec566e79e5c6b677fa6/xml/MAIN-SBP-AMD-EPYC-3-SLES15SP2.xml#L122

Hi Dario @dfaggioli 
can you clarify the following sentence:

This should be considered when tuning for <emphasis role="italic">Non-Uniform Memory Architecture (NUMA)</emphasis> as all memory accesses are not necessarily to local memory incurring a variable access penalty.

should it be:

This should be considered when tuning for <emphasis role="italic">Non-Uniform Memory Architecture (NUMA)</emphasis> as all memory accesses are not necessarily incurring a variable access penalty to local memory.

or: 

This should be considered when tuning for <emphasis role="italic">Non-Uniform Memory Architecture (NUMA)</emphasis> as all memory accesses are not necessary to local memory incurring a variable access penalty.

It is not completely clear currently. Thank you very much!

**Comment by chabowski** [comment]
@dfaggioli  Next sentence to clarify:  
      
"What is not obvious is the links to the IO die, but it should be taken into account when splitting a workload to optimize bandwidth to memory."

"Not obvious are the links to the IO die, but this (<the fact that the links are not obvious>) should be taken into account .... "
"Not obvious are the links to the IO die, but the IO die should be taken into account ...."

**Comment by chabowski** [comment]
@dfaggioli and one more: 

In addition to <package>lstopo</package> can provide the information, the level, size and ID of CPUs that share cache can be identified from the files under <filename>/sys/devices/system/cpu/cpuN/cache</filename>.

Options: 

"In addition to <package>lstopo</package> which can provide the information, the level, size and ID of CPUs that share cache can be identified from the files under <filename>/sys/devices/system/cpu/cpuN/cache</filename>."

"In addition, <package>lstopo</package> can provide the information, the level, size and ID of CPUs that share cache, which can be identified from the files under <filename>/sys/devices/system/cpu/cpuN/cache</filename>."

**Comment by dfaggioli** [comment]
> @dfaggioli Next sentence to clarify:
> 
> "What is not obvious is the links to the IO die, but it should be taken into account when splitting a workload to optimize bandwidth to memory."
> 
This sentence is right below the figure `fig-epyc-topology`. I think it means that it is not obvious, by looking at that figure, how the various CCXs/dies (which are shown in the figure itself) are connected to the IO die (which is not present in the figure because the tool does not draw it).

But again, @gormanm would be the one source of truth here. :-)

**Comment by dfaggioli** [comment]
> @dfaggioli and one more:
> 
> In addition to lstopo can provide the information, the level, size and ID of CPUs that share cache can be identified from the files under /sys/devices/system/cpu/cpuN/cache.
> 
> Options:
> 
> "In addition to lstopo which can provide the information, the level, size and ID of CPUs that share cache can be identified from the files under /sys/devices/system/cpu/cpuN/cache."
> 
> "In addition, lstopo can provide the information, the level, size and ID of CPUs that share cache, which can be identified from the files under /sys/devices/system/cpu/cpuN/cache."

This is still from @gormanm . Personally, I'd go for something like:

"In addition to the information that lstopo can provide, the level, size and ID of CPUs that share cache can be identified from the files under /sys/devices/system/cpu/cpuN/cache."

But we should really double check with him (plus, I'm no native Eng. speaker, so don't trust me!)

**Comment by gormanm** [comment]
> > https://github.com/SUSE/suse-best-practices/blob/c08df5286843d5ffe67a7ec566e79e5c6b677fa6/xml/MAIN-SBP-AMD-EPYC-3-SLES15SP2.xml#L122
> > 
> > Hi Dario @dfaggioli
> > can you clarify the following sentence:
> > This should be considered when tuning for Non-Uniform Memory Architecture (NUMA) as all memory accesses are not necessarily to local memory incurring a variable access penalty.
> 
> I think it means that it can happen that a memory operation accesses some remote (i.e., non-local) memory. That is, memory accesses not necessarily always happen to local memory, which mean they can incur a variable access penalty.
> 
> So, this, I would say:
> 
> > This should be considered when tuning for Non-Uniform Memory Architecture (NUMA) as all memory accesses are not necessary to local memory incurring a variable access penalty.
> 
> However, can we double check with @gormanm , as I think this comes from him ?

The switch from "necessarily" to "necessary" changes the semantics of the sentence. Alternative suggestion as follows

This should be considered when tuning for Non-Uniform Memory Architecture (NUMA) as all memory accesses may not reference local memory incurring a variable access penalty.

**Comment by gormanm** [comment]
> @dfaggioli and one more:
> 
> In addition to lstopo can provide the information, the level, size and ID of CPUs that share cache can be identified from the files under /sys/devices/system/cpu/cpuN/cache.
> 
> Options:
> 
> "In addition to lstopo which can provide the information, the level, size and ID of CPUs that share cache can be identified from the files under /sys/devices/system/cpu/cpuN/cache."
> 

This version is the best.

**Comment by gormanm** [comment]
> @dfaggioli Next sentence to clarify:
> 
> "What is not obvious is the links to the IO die, but it should be taken into account when splitting a workload to optimize bandwidth to memory."
> 
> "Not obvious are the links to the IO die, but the IO die should be taken into account ...."

This option is the better of the two. Thanks!
