### ISSUE TITLE
subtitle differences between pdf and html docs

### ISSUE THREAD

**Issue by jamesongithub** [SUSE/suse-best-practices#187]
Any reason why the pdf docs have the subtitle after the title
![image](https://user-images.githubusercontent.com/4452738/111530558-aad94100-8720-11eb-95d0-de8d7b8ab830.png)

while on the html it comes before?
![image](https://user-images.githubusercontent.com/4452738/111530571-af9df500-8720-11eb-8a57-bb70e2d7fe15.png)

Seems like subtitle should always be after?

**Comment by chabowski** [comment]
Hi @jamesongithub James, 
what you see first on HTML is not the subtitle, but the products and version numbers. 
Title is: Microsoft SQL Server on SUSE Linux Enterprise
Subtitle: Getting Started
Product names and versions: SUSE Linux Enterprise Server 12 SP3- SP5, Microsoft SQL Server 2019

Both look like they should. PDF has the product names below the line. 
On HTML, the product names/versions come first  - this is how our stylesheets are for all documentation, to make readers easily see the product name /version of the documentation they look at.

**Comment by jamesongithub** [comment]
i was using the subtitle term loosely, but yeah the version portion.

was just wondering why they differed.

**Comment by chabowski** [comment]
:-)
