### ISSUE TITLE
[doc] 2.2  Server registration

### ISSUE THREAD

**Issue by chabowski** [SUSE/suse-best-practices#190]
2.2  Server registration:

https://documentation.suse.com/sbp/all/html/TRD-sql-server-getting-started/index.html#server_registration

@jamesongithub reported that the Button "Copy Code" does not work throughout the paper.
Let's investigate what happened and how that can be fixed. Thanks!

**Comment by sknorr** [comment]
Fixed in suse-xsl. Highlight.js was unsetting the click handlers for these buttons.
