### ISSUE TITLE
DC-SBP-SAP-MULTI-SID broken after DAPS 3.1 update

### ISSUE THREAD

**Issue by sknorr** [SUSE/suse-best-practices#204]
DC-SBP-SAP-MULTI-SID uses several AsciiDoc attributes that are not defined. Previous versions of DAPS did not check for that but with 3.1, this issue is actually detected.

Unfortunately, in the case of DC-SBP-SAP-MULTI-SID, I was not certain what to replace these undefined attributes with. The issue is with the following attributes being used but not defined:

```
vip-ascs2
vip-ascs3
```

Maybe these are just misspellings of the existing attribute `:vip-asc2: 172.17.1.17` / `:vip-asc3: 172.17.1.27`?

Tagging @pirat013 with this, as you appear to be the main author of the document.

**Comment by pirat013** [comment]
@sknorr Thanks your are right. Could you please modify the string to match the variables?
Thanks Bernd

**Comment by sknorr** [comment]
Thanks for the feedback, fixed in d044700.
