### ISSUE TITLE
[doc] 1.1  Security for SAP HANA

### ISSUE THREAD

**Issue by EthanB11** [SUSE/suse-best-practices#211]
1.1  Security for SAP HANA:

https://documentation.suse.com/sbp/all/html/OS_Security_Hardening_Guide_for_SAP_HANA_SLES15/index.html#id-security-for-sap-hana

Link to http://help.sap.com/hana/SAP_HANA_Security_Guide_en.pdf does not work.

**Comment by chabowski** [comment]
@EthanB11 thanks very much for your comment! Seems the link has changed recently. 
For now, you can find the SAP document here:
https://help.sap.com/doc/eec734dbb0fd1014a61590fcb5411390/2.0.05/en-US/SAP_HANA_Security_Guide_en.pdf
This will be updated in the SLES15 Security Hardening Guide for SAP HANA and made available with the next build of the repository.

**Comment by chabowski** [comment]
Fixed in the document sources. Will be online after the next repo build.
