### ISSUE TITLE
Will there be a version of SAP_HA740_SetupGuide_AWS for SLES 15?

### ISSUE THREAD

**Issue by beng16ng** [SUSE/suse-best-practices#212]
:

https://documentation.suse.com/sbp/all/html/SAP_HA740_SetupGuide_AWS/index.html#

Will there be an updated document for SLES 15?

**Comment by chabowski** [comment]
@fmherschel @pirat013 can you please have a look at the question and give an answer? Thank you very much!

**Comment by fmherschel** [comment]
Sorry I have no date I could communicate.

**Comment by chabowski** [comment]
Thank you @fmherschel - but generally, would it be on the the list of papers to update to SLES15? Thanks!!

**Comment by fmherschel** [comment]
@chabowski This needs to be decided SUSE internally and also together with the cloud partner.

**Comment by chabowski** [comment]
@fmherschel thank you very much Fabian, for your answers!

**Comment by syu8** [comment]
Please refer SAP on AWS Technical Documentation for the SAP NetWeaver HA on AWS Configuration Guide for SLES and RHEL. https://docs.aws.amazon.com/sap/latest/sap-netweaver/sap-netweaver-ha-configuration-guide.html. Please click on "PDF" to access the full document.

**Comment by lpinne** [comment]
@syu8 thanks!
I think this solves the issue.
