### ISSUE TITLE
[doc] 3.4  The Concept of the Performance Optimized Scenario

### ISSUE THREAD

**Issue by lpinne** [SUSE/suse-best-practices#216]
3.4  The Concept of the Performance Optimized Scenario:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-12/#id-the-concept-of-the-performance-optimized-scenario
---
You can configure the level of automation by setting the parameter AUTOMATED_REGISTER. If automated registration is activated the cluster will also automatically register a former failed primary to get the new secondary.
---

Please double check if that is going to work on SLES-for-SAP 12, SAPHanaSR-ScaleOut version 0.16x.
AFAIK this breaks tracing of system replication with 0.16x. It needs multi-target support, which comes for SLES-for-SAP 15 with 0.180.

**Comment by chabowski** [comment]
Hi @fmherschel and @pirat013 
Could you please have a look at the comment from Lars and see if this needs to be changed?
Thank you very much! Meike

**Comment by chabowski** [comment]
resolved

**Comment by fmherschel** [comment]
However Lars should work with me to solve such issues :-) I was ooo at this time.
