### ISSUE TITLE
[doc] 1.1.4  The Concept of the Cost Optimized Scenario - misspelled word

### ISSUE THREAD

**Issue by jhhudso** [SUSE/suse-best-practices#218]
1.1.4  The Concept of the Cost Optimized Scenario:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-CostOpt-12/#id-the-concept-of-the-cost-optimized-scenario

Word, 'example' misspelled as 'exaample' in the following sentence:

"In addition to the description of the concept in this best practice document, read the corresponding SAP documentation such as "Using Secondary Servers for Non-Productive systems". The section is available for exaample for SAP HANA 2.0 SPS05 at https://help.sap.com/viewer/6b94445c94ae495c83a19646e7c3fd56/2.0.05/en-US/5447545b91a04cf8a0d6133a026f2be5.html."

**Comment by fmherschel** [comment]
@jhhudso Thanks for reporting

**Comment by fmherschel** [comment]
Fixed in my repo (fork) so will be fixed hopefully with the next update.
