### ISSUE TITLE
[doc] 1.1.4  The Concept of the Performance Optimized Scenario

### ISSUE THREAD

**Issue by jhhudso** [SUSE/suse-best-practices#230]
1.1.4  The Concept of the Performance Optimized Scenario:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-12/#id-the-concept-of-the-performance-optimized-scenario

Using the SAP HANA hook described in this document allows to inform the cluster immediately if the SAP HANA system replication brakes.

should be

Using the SAP HANA hook described in this document allows to inform the cluster immediately if the SAP HANA system replication breaks.

**Comment by chabowski** [comment]
Hi @jhhudso Very good catch of a really "funny" typo :-). Thank you very much, this will be fixed soon. Kind regards - Meike
