### ISSUE TITLE
[doc] 7.4  Manual Test of SAP HANA SR Takeover

### ISSUE THREAD

**Issue by jschaef** [SUSE/suse-best-practices#237]
7.4  Manual Test of SAP HANA SR Takeover:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-CostOpt-12/index.html#id-manual-test-of-sap-hana-sr-takeover

Please give an example for each step.

**Comment by chabowski** [comment]
@fmherschel @lpinne Hi Fabian and Lars, would you mind having a look at this issue? I will mark it as enhancement. Thank you very much! Kind regards, Meike

**Comment by fmherschel** [comment]
@chabowski Sorry no time to do that.
