### ISSUE TITLE
[doc] 7.5  Testing the hook integration

### ISSUE THREAD

**Issue by pinaronald** [SUSE/suse-best-practices#239]
7.5  Testing the hook integration:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-scaleOut-PerfOpt-15/index.html#id-testing-the-hook-integration

There is a typo, the correct regex should be: 
```
- suse01:ha1adm> awk  '/ha_dr_SAPHanaSR.*crm_attribute/ \
+ suse01:ha1adm> awk  '/ha_dr_SAPHanaSr.*crm_attribute/ \
```
Which output similar to:
```
2021-12-10 23:52:16.388254 ha_dr_SAPHanaSrM 2.0
2021-12-10 23:52:16.829596 ha_dr_SAPHanaSrM SOK
```

**Comment by chabowski** [comment]
@fmherschel @lpinne when you find time, could you have a quick look? Currently we have as regex with output the following:

`----
{mySite1FirstNode}:ha1adm> cdtrace
{mySite1FirstNode}:ha1adm> awk  '/ha_dr_SAPHanaSR.*crm_attribute/ \
     { printf "%s %s %s %s\n",$2,$3,$5,$16 }' nameserver_{mySite1FirstNode}.*
2021-05-04 12:34:04.476445 ha_dr_SAPHanaS.*SFAIL
2021-05-04 12:53:06.316973 ha_dr_SAPHanaS.*SOK
----`

Thank you!

**Comment by chabowski** [comment]
@pinaronald the issue should be fixed, the updated document will be available by the end of this week.
@fmherschel thank you very much!

Closing the issue.
