### ISSUE TITLE
[doc] 2  Supported scenarios and prerequisites

### ISSUE THREAD

**Issue by lpinne** [SUSE/suse-best-practices#245]
2  Supported scenarios and prerequisites:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-CostOpt-15/#cha.hana-sr.scenario

minor typo:  
"srConnectionChanegd()" should be "srConnectionChanged()"

Regards,
Lars

**Comment by lpinne** [comment]
SLES4SAP-hana-sr-guide-CostOpt-12.adoc
is also affected

**Comment by chabowski** [comment]
This issue is fixed in both documents. SBP repo will most probably be rebuilt today. Closing the issue. Thank you very much!
