### ISSUE TITLE
[doc] Example&nbsp;1:  Installing additional software for the HA cluster 

### ISSUE THREAD

**Issue by emilianolangella** [SUSE/suse-best-practices#246]
Example&nbsp;1:  Installing additional software for the HA cluster :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-1.7.5.4.3

"supportutil-plugin-ha-sap" should be "supportutils-plugin-ha-sap".

**Comment by fmherschel** [comment]
Thanks for reporting, we will change that as soon as possible.

**Comment by chabowski** [comment]
-This is fixed and merged. Closing issue. Thank you very much!
