### ISSUE TITLE
[doc] 6.2.6  Restarting ASCS In-Place Using Stop and Start

### ISSUE THREAD

**Issue by pankb19** [SUSE/suse-best-practices#248]
6.2.6  Restarting ASCS In-Place Using Stop and Start:

https://documentation.suse.com/sbp/all/html/SAP_S4HA10_SetupGuide-SLE12/index.html#id-restarting-ascs-in-place-using-stop-and-start

when I am manually stopping ASCS using stopsap / sapcontrol -nr 00 -function Stop, ASCS node is moving to another node, but in guide its mention 
"6.2.6 Restarting ASCS In-Place Using Stop and Start REPORT DOCUMENTATION BUG#
Check if the in-place restart of the SAP resources have been processed correctly. The SAP instance should not failover to an other node, it must start on the same node where it has been stopped.
As user en2adm, do the following:"

Is this test need to be done while maintenance mode?

Thanks
Pankaj

**Comment by chabowski** [comment]
Thank you @pankb19 for reporting your issue. 

@fmherschel @lpinne would you mind having a look at the issue? Thank you very much! Kind regards - Meike

**Comment by lpinne** [comment]
Hi Pankaj,

as all sapcontrol operations, local restart should work with active cluster.
This the idea behind sap-suse-cluster-connector, and pre-requisite for SAP HA cluster certification.

If that test does not work as expected, that usually indicates an issues with either the test procedure
or with the setup. Basis is proper integration of sap-suse-cluster-connector.
Common mistakes are left-over migration constraints in CIB. Unfortunately lately
a certain version of sap-suse-cluster-connector caused a problem with migration constraints.
So you might look into this direction. You als might imagine opening a support request with SUSE
support services to get the problem fixed.

Hope this helps to some degree at least.

Regards,
Lars

**Comment by pankb19** [comment]
hi Lars,

thanks a lot
