### ISSUE TITLE
[doc] 8.1  Installing the cluster packages

### ISSUE THREAD

**Issue by wtmpx** [SUSE/suse-best-practices#259]
8.1  Installing the cluster packages:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-installing-the-cluster-packages

The package name with capital S: SAPHanaSR-ScaleOut

**Comment by fmherschel** [comment]
Nice finding, we will fix that in the next version.

**Comment by lpinne** [comment]
fixed.
thanks for reporting!
