### ISSUE TITLE
[doc] 7.1  Implementing the HA/DR provider hook SAPHanaSrMultiTarget.py

### ISSUE THREAD

**Issue by wtmpx** [SUSE/suse-best-practices#260]
7.1  Implementing the HA/DR provider hook SAPHanaSrMultiTarget.py:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-implementing-the-hadr-provider-hook-saphanasrmultitarget-py

This step should be moved forward because the srHook coming from SAPHanaSR-ScaleOut package and this will be installed in next section.

**Comment by fmherschel** [comment]
@wtmpx We will have a look in that. Thanks for reporting. While your other issue was quite easy to solve (I already created commits) this one needs to be checked more carefully. Maybe we need to install the package already in this step rather then moving the hook implementation to a later step to avoid to much restarts of SAP HANA.

**Comment by fmherschel** [comment]
@lpinne We need to discuss that issue some times later.

**Comment by lpinne** [comment]
Hi,

the package SAPHanaSR-ScaleOut gets installed at step 4.1.2 
https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-installing-additional-software
So the hook script is in place at step 7.1

In fact installing the packae during step 8.1 is not neccessary.
https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-installing-additional-software
However, the mentioned command will not change anything, just inform that the package already is installed. We might remove that line for the next version.

Regards,
Lars
