### ISSUE TITLE
[doc] 13.2  Example Cluster Configuration

### ISSUE THREAD

**Issue by roseswe** [SUSE/suse-best-practices#261]
13.2  Example Cluster Configuration:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-12/#id-example-cluster-configuration

record-pending=true
This is for ENSA1/2 cluster important, but for HANA SRA cluster record-pending should be "=false"

**Comment by fmherschel** [comment]
@roseswe No this has always been tested with exactly that setting. And it is also what the new toolset for SLES is doing by default. At least in all my tests so far. We asked about the change of the default record-pending=true (prior it was false) and we got the feedback that now the better tested twig of the code is with record-pending=true. You are right in the past record-pending=false was the default (SLE11 code base or so). And you are right that for scenarios using sap_suse_cluster_connector the value true is a MUST. Here it is just the unchanged default.

**Comment by lpinne** [comment]
Hi,
man page SAPHanaSR_basic_cluster(7) says record_pending=true.
Man page SAPHanaSR-ScaleOut_basic_cluster says =true for SLE 12 and 15, but =false for 11.
We are doing our internal tests with =true.
Regards,
Lars
