### ISSUE TITLE
[doc] 8.2  Configuring the basic cluster

### ISSUE THREAD

**Issue by wtmpx** [SUSE/suse-best-practices#263]
8.2  Configuring the basic cluster:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-configuring-the-basic-cluster

while I find this section very good, it is a duplicate of our HAE documentation. 
Let us guide customer to check the Quick Setup guide e.g., https://documentation.suse.com/sle-ha/15-SP3/single-html/SLE-HA-installation/ 

or the full documentation: https://documentation.suse.com/sle-ha/12-SP5/single-html/SLE-HA-guide/#book-sleha 

and of-course we keep the SAP HANA settings here. 

Thanks

**Comment by fmherschel** [comment]
@wtmpx The setup-guide should lead to the running cluster. In the references we point to the full product documentation. So in my opinion the current way to describe the cluster in the guide is as it should be. We need to balance between adding to much variants in the setup guide on one hand and on always pointing out to other documents at to much places as this breaks the user experience. So for me that will most likely be a wont'fix as it is not broken in my POV.

**Comment by wtmpx** [comment]
@fmherschel Okay, let me close it, I agree with you.
