### ISSUE TITLE
[doc] 8.3.1  Cluster bootstrap and more

### ISSUE THREAD

**Issue by wtmpx** [SUSE/suse-best-practices#264]
8.3.1  Cluster bootstrap and more:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-cluster-bootstrap-and-more

Please remove 
cluster-name=hacluster \ 
from crm-bs.txt ; it will overwrite customer setting.

**Comment by fmherschel** [comment]
@wtmpx Again the setup-guide describes a tested, validated and working solution. If you like to have an other cluster name you are free to enter it either in the crm-bs.txt or to skip it.

**Comment by fmherschel** [comment]
@wtmpx we will discuss, if we will follow your hint or not.

**Comment by lpinne** [comment]
Hi,

the setup guide explains step-by-step how to install and cofigure the HA cluster.
Thus any of our crm snippets may overwrite existing values.
None of the documented instance names, SIDs, IP addresses, hostnames, cluster names
is intended to match a given customer situation.
If the customer follows the guide they will get a working test cluster.
If the customer does anything in parallel or leaves out certain steps, they are on their own.
Of course the customer can change the cluster name to something that fits their needs, as long as it matches pacemaker rules for cluster names. 

Regards,
Lars
