### ISSUE TITLE
[doc] 8.4.1  Verifying the communication between the hook and the cluster

### ISSUE THREAD

**Issue by wtmpx** [SUSE/suse-best-practices#265]
8.4.1  Verifying the communication between the hook and the cluster:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-verifying-the-communication-between-the-hook-and-the-cluster

In test I got this error: crm_attribute -G  -n hana_<sid>_glob_srHook 
Error performing operation: No such device or address

Looking at my configuration I see: 
	hana_so1_glob_upd=ok \
	hana_so1_glob_sync_state=SOK \
	hana_so1_glob_sec=SiteB \
	hana_so1_glob_prim=SiteA \
	hana_so1_glob_op_mode=logreplay

Should we change srHook with sync_state ?

**Comment by wtmpx** [comment]
Hi Lars, 

I missed pasting it in github. 

# crm_attribute -G  -n hana_so1_glob_srHook
scope=crm_config  name=hana_so1_glob_srHook value=(null)
Error performing operation: No such device or address

Regards,
Ahmad

**Comment by wtmpx** [comment]
Hi Fabian, 

Yes, I'm using SAPHanaSrMultiTarget.py ; not the old srHook: SAPHanaSR.py

**Comment by wtmpx** [comment]
Hi Lars, 

I kill the nameserver and cluster moved HANA to SiteB. And now I see this:

crm_attribute -G  -n hana_so1_glob_srHook
scope=crm_config  name=hana_so1_glob_srHook value=SWAIT

Should we add something here https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-verifying-the-communication-between-the-hook-and-the-cluster regarding this? 

Thanks 
Ahmad

**Comment by lpinne** [comment]
Hi Ahmad,

1) It is general characteristic of crm/CIB to show such a message in case the attribute does not exists. This is not specific to SAPHanaSR.py.
2) The guide already mentions how to check HANA traces and Linux messages for HANA HADR events and
related CIB access. Manual pages SAPHanaSR-ScaleOut(7) and SAPHanaSR.py(7) are explaining
when and how the hook script is called and what is does. The manual pages are referenced in the guide. 
3) We have ben told by management to keep the setup guides short.

Regards,
Lars

**Comment by wtmpx** [comment]
Hi Lars, 
Sure. Just I am saying step 8.4.1 will not work as written in the docs because in the guide the test section coming later. 

Thanks,
Ahmad

**Comment by lpinne** [comment]
Hi Ahmad,

in step 7.5 the HANA is restarted to implement and test the hooks
( https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-starting-sap-hana )

At that point the srHook status is written into a hidden file. Once the cluster activate the SAPHana RA, the CIB attribute srHook is written according to that file. See man page SAPHanaSR.py(7). 

If there is no CIB attribute srHook, the previous steps for integrating the hooks have not been done as described. E.g. the hooks have been implemented without restarting HANA.

Regards,
Lars
