### ISSUE TITLE
[doc] Example&nbsp;4:  Installing PCM from source 

### ISSUE THREAD

**Issue by twillhal** [SUSE/suse-best-practices#266]
Example&nbsp;4:  Installing PCM from source :

https://documentation.suse.com/sbp/sap/html/SBP-SLES4SAP-sap-infra-monitoring/index.html#id-1.5.5.3

PCM has recently switched to cmake. You should update the build instructions accordingly:
mkdir build
cd build
cmake ..
cmake --build .

Furthermore, the ".x" has been dropped from the binary name, i.e. it is now called "pcm-sensor-server" only.

**Comment by chabowski** [comment]
@gereonvey could you please have a look at the issue and let me know if you would like to open a PR, or if I should fix it according to the instructions from @twillhal . Thank you!

**Comment by gereonvey** [comment]
@chabowski I tested the build and adapted the instructions accordingly.

**Comment by chabowski** [comment]
updated document will be published with the next public build of the SBP repository. Thanks all!
