### ISSUE TITLE
[doc] 8.1  Implementing the Python Hook SAPHanaSR

### ISSUE THREAD

**Issue by m0rbo** [SUSE/suse-best-practices#271]
8.1  Implementing the Python Hook SAPHanaSR:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#id-implementing-the-python-hook-saphanasr

Based on various bugs i've discovered today, srHooks are not valid and working with HANA 1.0.
https://bugzilla.suse.com/show_bug.cgi?id=1182201
https://bugzilla.suse.com/show_bug.cgi?id=1178017
https://bugzilla.suse.com/show_bug.cgi?id=1169184

Can we make this more clear in the srHook section of the documentation?

The Prereqs section doesn't seem to cover that srHooks are not valid for HANA 1.0, but yet we mention HANA 1.0 in the prereq section:
https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#cha.hana-sr.scenario

**Comment by chabowski** [comment]
@fmherschel @lpinne would you mind having a look at this one, too? If verified, does this impact other versions of the doc for SLES15 etc? Thank you!

**Comment by lpinne** [comment]
Hi m0rbo,

good point.
1. In fact HANA 1.0 should be out of support from SAP now.
2. You can run a cluster without SAPHanaSR. That is not recommended, but possible. Was the only way for some years.
3. The complete requirements are listed in man pages SAPHanaSR(7) and SAPHanaSR.py(7). Both are referenced in the setup guide.

We are just about updating the SAP HANA scale-up perf-opt guide. I will try to improve the requirements section.

Please understand that we need to limit the setup guide to some degree.
You always can look into the manual page for more details. If something is missing there, please open a bug against the SAPHanaSR package.

Thank for your report!
Regards,
Lars

**Comment by m0rbo** [comment]
Hi Thanks for the info Lars.
Just wanted to point out that currently the man page also seems to be wrong.
Current man page (man SAPHanaSR.py) states: 
"REQUIREMENTS
       1. SAP HANA starting with version 1.0 SPS 11 patch level 112.02.  Older versions do not provide the srHook method srConnectionChanged()."

Which also is not valid?

However, I understand this bug was created to address that:
https://bugzilla.suse.com/show_bug.cgi?id=1182201
Not sure why the updates in this bug have taken so long to be released.

**Comment by lpinne** [comment]
Hi m0rbo,

it has been a little complicated in the past:
1. HANA 1.0 prior to patch level 112 do not support srConnectionChanged() at all
2. HANA 1.0 patch level 112.02 supports srConnectionChanged(), but not multi-target replication.
3. SAPHanaSR.py in SAPHanaSR-ScaleOut 0.16x is without mult-target replication
4. SAP HANA 2.0 SPS 04x supports srConnectionChanged() with multi-target replication
5. SAPHanaSR.py in SAPHanaSR 0.15x is with multi-target
6. SAPHanaSrMultiTarget.py in SAPHanaSR-ScaleOut 0.180 is with multi-target

It is easy today:
1. HANA 1.0 is not longer supported by SAP
3. HANA 2.0 supports multi-target
4. SAPHanaSR.py in SAPHanaSR 01.5x supports multi-target
5. SAPHanaSrMultiTarget.py in SAPHanaSR-ScaleOut 0.18x supports multi-target

Hope this helps a little.
Regards,
Lars
