### ISSUE TITLE
Broken links in many SAP setup guides

### ISSUE THREAD

**Issue by chabowski** [SUSE/suse-best-practices#273]
Hi @lpinne and @fmherschel, 

we found broken links for two specific SAP documents/resources which are referenced in several SAP setup guide SBPs.

- SAP_HA740_SetupGuide_AWS.adoc
- SAP-NetWeaver-7.50-SLE-15-Setup-Guide-AliCloud.adoc
- sap-nw740-sle15-setupguide.adoc
- SAP_NW740_SLE12_SetupGuide/index.html
- SAP_S4HA10_SetupGuide_SLE12.adoc
- SAP-S4HA10-setupguide-sle15.adoc

The broken links are: 

- SAP HANA TDI: https://www.sap.com/documents/2015/03/74cdb554-5a7c-0010-82c7-eda71af511fa.html
For this one I found an alternative link which I assume is correct to be referenced:
https://archive.sap.com/kmuuid2/80e422ef-e3bd-3210-2a92-f133259bdfbf/SAP%20HANA%20TDI%20-%20Overview.pdf

- SAP HANA Hardware Directory: https://www.sap.com/documents/2015/03/74cdb554-5a7c-0010-82c7-eda71af511fa.html
I could not find an alternative URL. 

Could you please check and verify / approve the alternative URL, and let me know what to do with the other broken link? 
I will then update the documents accordingly. 

Thank you very much!! :-)

**Comment by fmherschel** [comment]
@chabowski I need some time to check those links. In parallel @lpinne also works on changes of setup guides.
@lpinne I (Fabian) will work on this task here so we do not get an  overlap.

**Comment by lpinne** [comment]
Hi Meike, hi Fabian,

1. I will check if this guides are affected and will suggest fixes:
     - SAP-S4HA10-setupguide-sle15.adoc
     - sap-nw740-sle15-setupguide.adoc
    BTW: Should it be "SAP-NW740" or "sap-s4ha10"?

2. SLE12 guides should not be changed anymore:
    - SAP_NW740_SLE12_SetupGuide/index.html
    - SAP_S4HA10_SetupGuide_SLE12.adoc
    - SAP_HA740_SetupGuide_AWS.adoc

3. This guide needs discussion with the cloud team:
    - SAP-NetWeaver-7.50-SLE-15-Setup-Guide-AliCloud.adoc

Regards,
Lars

**Comment by chabowski** [comment]
Hi @lpinne @fmherschel: all six guides that are affected by the broken links are listed on top in the first comment. 

Please do not rename the existing guides yourself. This is something I will do over time (and this is mainly for better Search Engine Optimization) to the lower case file name versions, not using underscores. But each renamed document needs a redirect on our publication server DocServ which needs to be included manually to avoid broken links in other documents, or broken bookmarks. This is quite some work, and Tom currently has no capacity to do that on a bigger scale. This is the reason why I am doing it "in the long run" and when there is a bit of time for such things. 

Thank you very much!!

**Comment by chabowski** [comment]
Hi @lpinne you can just leave it to me - I will update the broken links as I have a bigger list with other SBPs, too, that have broken links. I just needed confirmation which URLs to refer to for the broken links :-). Once again, thank you very much!

**Comment by chabowski** [comment]
Broken links in all papers above are fixed. Closing issue.
