### ISSUE TITLE
[doc] 13.2  Example cluster configuration

### ISSUE THREAD

**Issue by pinaronald** [SUSE/suse-best-practices#278]
13.2  Example cluster configuration:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-costopt-15/index.html#id-example-cluster-configuration

Most probably a copy/paste mistake, but the negative location constraint should address QAS instance not HA1:

```
  - location loc_QAS_never_on_suse01 rsc_SAP_HA1_HDB10 -inf: suse01
 + location loc_QAS_never_on_suse01 rsc_SAP_QAS_HDB20 -inf: suse01
```

**Comment by fmherschel** [comment]
@pinaronald Thanks for this report. I will have a look on this soon as soon as ... p.

**Comment by fmherschel** [comment]
Ok I see in the explained example it is ok but it is wrong in the complete dump of the crm config.

**Comment by fmherschel** [comment]
As we are using variables, unfortunately we used the variables for the SR system, not for the non-replicated-system.

**Comment by fmherschel** [comment]
Closing issue.

**Comment by pinaronald** [comment]
Thank you Fabian, much appreciated!
