### ISSUE TITLE
[doc] 13.2  Example Cluster Configuration

### ISSUE THREAD

**Issue by roseswe** [SUSE/suse-best-practices#286]
13.2  Example Cluster Configuration:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-12/#id-example-cluster-configuration

Mismatch of 2000: points and Optional:

Snippet:
# vi crm-cs.txt
# enter the following to crm-cs.txt

colocation col_saphana_ip_HA1_HDB10 2000: rsc_ip_HA1_HDB10:Started \
    msl_SAPHana_HA1_HDB10:Master
order ord_SAPHana_HA1_HDB10 Optional: cln_SAPHanaTopology_HA1_HDB10 \
    msl_SAPHana_HA1_HDB10

But on reference it is 2000

I assume meanwhile optional is the suggested value?

**Comment by lpinne** [comment]
Hi Ralph,

the SLE12 guides have been written a while a go. At that time, 2000 was needed.
If 2000 does not work anymore that would be a regression in pacemaker.

We are now focussing on SLE15 for new deployments. There we recommend "optional".

Regards,
Lars

**Comment by fmherschel** [comment]
@roseswe We even have "Optional:" already in our document:
`# vi crm-cs.txt
# enter the following to crm-cs.txt

colocation col_saphana_ip_HA1_HDB10 2000: rsc_ip_HA1_HDB10:Started \
    msl_SAPHana_HA1_HDB10:Master
order ord_SAPHana_HA1_HDB10 Optional: cln_SAPHanaTopology_HA1_HDB10 \
    msl_SAPHana_HA1_HDB10`

Only the addendum was unfortunately not updated. But that is not part of the documentation of the setup of the cluster  but only an example of a cluster been set-up in the past.
