### ISSUE TITLE
[doc] 8  Set Up SAP HANA HA/DR providers

### ISSUE THREAD

**Issue by andreas-mach** [SUSE/suse-best-practices#287]
8  Set Up SAP HANA HA/DR providers:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-12/#id-set-up-sap-hana-hadr-providers

---

I'm missing the subchapters - also for SBP - SLE 15:

4. Start SAP HANA

5. Test the hook integration

Thx

**Comment by chabowski** [comment]
Hi again, @fmherschel and @lpinne - would you mind checking this issue? Are there steps / chapters missing? Thank you very much for your help!

**Comment by fmherschel** [comment]
@chabowski Missing? - no - available ?- also no. So what? Oh they just have been skipped to be written ,-)

**Comment by fmherschel** [comment]
For SLE15 code base fixed and published.
