### ISSUE TITLE
[doc] 8  Set Up SAP HANA HA/DR providers

### ISSUE THREAD

**Issue by wtmpx** [SUSE/suse-best-practices#290]
8  Set Up SAP HANA HA/DR providers:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#id-set-up-sap-hana-hadr-providers

The following two sections are missing:
Start SAP HANA
Test the hook integration

**Comment by chabowski** [comment]
This is known and will be addressed over time.
