### ISSUE TITLE
[doc] Example&nbsp;2:  Simple backup for the system database and all tenants with one single backup call 

### ISSUE THREAD

**Issue by varkoly** [SUSE/suse-best-practices#292]
Example&nbsp;2:  Simple backup for the system database and all tenants with one single backup call :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-1.9.6.3
This command do not work in any case:
hdbsql -u SYSTEM -d SYSTEMDB \
   "BACKUP DATA FOR FULL SYSTEM USING FILE ('backup')"

The command should be called:
hdbsql -i 10 -u SYSTEM -d SYSTEMDB \
   "BACKUP DATA FOR FULL SYSTEM USING FILE ('backup')"

**Comment by lpinne** [comment]
see https://github.com/SUSE/suse-best-practices/pull/384
