### ISSUE TITLE
[doc] Table&nbsp;3:  SBD Options in File /etc/sysconfig/SBD 

### ISSUE THREAD

**Issue by m0rbo** [SUSE/suse-best-practices#293]
Table&nbsp;3:  SBD Options in File /etc/sysconfig/SBD :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-1.11.5.5.4.4

Typo in this paragraph:
SBD_WATCHDOG_TIMEOUT
"This parameter must match your storage environemt."
"environemt"
should be "environment"

**Comment by chabowski** [comment]
Thank you, this has been fixed and will be published with the next build of the repo.
