### ISSUE TITLE
[doc] Figure&nbsp;3:  The five main topics of the OS Security Hardening for HANA 

### ISSUE THREAD

**Issue by ajaeger** [SUSE/suse-best-practices#294]
Figure&nbsp;3:  The five main topics of the OS Security Hardening for HANA :

https://documentation.suse.com/sbp/sap/single-html/OS_Security_Hardening_Guide_for_SAP_HANA_SLES15_SP2_and_later/#id-1.3.8.3

Typo: "O pen" in "O pen source software is frequently reviewed and tested"

**Comment by chabowski** [comment]
Thank you @ajaeger this is fixed and will be published with the next repo update
