### ISSUE TITLE
[doc] 3.5  Important prerequisites

### ISSUE THREAD

**Issue by varkoly** [SUSE/suse-best-practices#296]
3.5  Important prerequisites:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-important-prerequisites

Some prerequisites were listed twice:

"All SAP HANA instances controlled by the cluster must not be activated via sapinit auto-start."  and "Automated start of SAP HANA instances during system boot must be switched off."  mean the same thing. One of them can be deleted.

As the last point stands: "You need at least SAPHanaSR-ScaleOut version 0.180, SUSE Linux Enterprise Server for SAP Applications 15 SP1 and SAP HANA 2.0 SPS 4 for all mentioned setups." In two other points the same reqirement is mentioned.  I propose following changes:

1. Set "You need at least SAPHanaSR-ScaleOut version 0.180, SUSE Linux Enterprise Server for SAP Applications 15 SP1 and SAP HANA 2.0 SPS 4 for all mentioned setups."  as the first prerequisite.
2. Remove point "For SAP HANA databases without additional master name server candidate, the package SAPHanaSR-ScaleOut version 0.180 or newer is needed."
3. Remove text "For SAP HANA multi-tier and multi-target system replication, the package SAPHanaSR-ScaleOut version 0.180 or newer is needed."

**Comment by lpinne** [comment]
Hi Peter,
thank your for your suggestions!
1) Regarding autostart: I am aware of several ways for starting a SAP instance at boot. Besides the mentioned instance profile parameter, there is selfmade rc-scripts and systemd units as well as 3rd party systems mgmt, e.g. LAMA.
2) The version requrrements are mentioned several times by intention. We want to make sure it appears in the overview as well as in the detailled list. Besides that, the details have been added one by one, taken from different sources (man pages). The idea is to keep them in sync with the respective sources to make later changes and checks more easy.
Regards,
Lars
