### ISSUE TITLE
[doc] Example&nbsp;5:  SSH key creation and exchange 

### ISSUE THREAD

**Issue by varkoly** [SUSE/suse-best-practices#297]
Example&nbsp;5:  SSH key creation and exchange :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-1.7.6.3.4

This is IMHO senceless:
"After collecting all host keys store them in a file named authorized_keys. Push the entire directory /root/.ssh/ from the first node to all further cluster members."
In authorized_keys should be saved the id_rsa.pub if the customer want to have passwordless ssh connection. This should be discusses if it is secure.

**Comment by fmherschel** [comment]
Thanks for your fix! I need to also transfer that to other guides, I will open an own issue for that.
