### ISSUE TITLE
[doc]  

### ISSUE THREAD

**Issue by anmozz** [SUSE/suse-best-practices#302]
:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#id-1.12.6.7.2.4

On example 19, recovery procedure, point 2:
mistaken:
Restart the HANA database (now secondary) on node **1** as root.
should be:
Restart the HANA database (now secondary) on node **2** as root.

**Comment by chabowski** [comment]
Of course the same is valid for this issue ;-) ... And probably we should then check the other docs specifically for this??
(from #301 @fmherschel @lpinne would you please have a quick look and verify? I would then fix that issue. Thanks!)

**Comment by lpinne** [comment]
Hi,

anmozz is right here as well.
Since the database has been killed on node2, it needs to be registered and started on node2.

The recovery is different on scale-up cost-optimized.
Nevertheless the scale-up cost-opt guide might be checked.

Regards,
Lars

**Comment by chabowski** [comment]
Bug is fixed, also in the document for version 12. Changes will be visible with the next build of the repo. Closing bug.
