### ISSUE TITLE
[doc] SLSA provenance examples

### ISSUE THREAD

**Issue by behnazh-w** [SUSE/suse-best-practices#304]
I have read [this article](https://documentation.suse.com/sbp/server-linux/html/SBP-SLSA4/index.html) on how all SUSE products are compliant with most of the requirements at level 4. Based on this article SUSE build pipelines already generate SLSA provenances. 

I would like to download a sample provenance and test/verify it. Where can I find the relevant instructions and examples?

**Comment by chabowski** [comment]
@janajaeger @msmeissn would you mind having a look and see if you can answer Behnaz' request? Thank you very much!

**Comment by msmeissn** [comment]
For the record, our processes have been adjusted to be SLSA level 4 compliant and we started shiping provenance only for new build packages with SLES 15 SP4.

An publically downloadable provenance file e.g. would be here:

http://download.opensuse.org/update/leap/15.4/sle/x86_64/bsdtar-3.5.1-150400.3.3.1.x86_64.slsa_provenance.json
this is the signed json format, the payload as base64 decoded can be decoded also to the payload json attestation.

**Comment by behnazh-w** [comment]
Thanks for the provenance example. Is there any documentation for the provenance verifier?

**Comment by msmeissn** [comment]
We currently do not have such documentation yet. (and not sure about tooling)

We currently work adjustments to tooling where outside people can use our build tool with provnenance file as input to rebuild packages.

**Comment by behnazh-w** [comment]
Thanks. So, at the moment users can't verify whether the provenance has been contaminated or not. Looks like the only [provenance requirement ](http://slsa.dev/spec/v0.1/requirements#provenance-requirements) that would be satisfied is the `Available ` requirement at level 1, and other requirements, such as `Authenticated`, and `non-falsifiable` at higher levels will not be satisfied, is that correct?

**Comment by adrianschroeter** [comment]
you saw the signatures inside of the provenance files? This are signatures of the payload done with the same signing key as used for entire distro (SLES in this case).

Please note that the in-toto tooling is not yet supporting version 0.2 of the SLSA spec, but I would expect that it can be used to verify these files soon.
