### ISSUE TITLE
[doc] 2.2.3  Forwarding syslog files to a central syslog server

### ISSUE THREAD

**Issue by OtharSmirnow** [SUSE/suse-best-practices#308]
2.2.3  Forwarding syslog files to a central syslog server:

https://documentation.suse.com/sbp/sap/html/OS_Security_Hardening_Guide_for_SAP_HANA_SLES15/index.html#id-forwarding-syslog-files-to-a-central-syslog-server

Issue: Document formatting error
This section contains two recommendations:
Forwarding syslog ... and Disabling ctrl-alt-del

**Comment by chabowski** [comment]
@abergmann could you and Soeren please have a look at this issue? Thank you!

**Comment by scmschmidt** [comment]
https://github.com/SUSE/suse-best-practices/pull/316 should fix the issue in both documents ("OS_Security_Hardening_Guide_for_SAP_HANA_SLES12" and "OS_Security_Hardening_Guide_for_SAP_HANA_SLES15")

**Comment by chabowski** [comment]
Thank you - closing the issue. Fix will be visible with the next public build of the repo.
