### ISSUE TITLE
[doc] 1.2  Security for SUSE Linux Enterprise Server

### ISSUE THREAD

**Issue by ajaeger** [SUSE/suse-best-practices#311]
1.2  Security for SUSE Linux Enterprise Server:

https://documentation.suse.com/sbp/sap/html/OS_Security_Hardening_Guide_for_SAP_HANA_SLES15_SP2_and_later/index.html#id-security-for-suse-linux-enterprise-server

" Currently we are in the process of achieving the same for SUSE Linux Enterprise Server 15"

The EAL 4+ certification for SLES 15 is done, could you update the above sentence, please?

**Comment by chabowski** [comment]
Fixed - changed information. Thank you!
