### ISSUE TITLE
[doc] 1.3  About this document

### ISSUE THREAD

**Issue by ajaeger** [SUSE/suse-best-practices#312]
1.3  About this document:

https://documentation.suse.com/sbp/sap/html/OS_Security_Hardening_Guide_for_SAP_HANA_SLES15_SP2_and_later/index.html#id-about-this-document

Typo:
"Security updates & patches

    O pen source software"

There's an extra space in "O pen"

**Comment by chabowski** [comment]
fixed - thank you!
