### ISSUE TITLE
[doc] Example 16:  Entry in sudo permissions /etc/sudoers.d/SAPHanaSR file - could be more secure

### ISSUE THREAD

**Issue by yeoldegrove** [SUSE/suse-best-practices#315]
Example&nbsp;16:  Entry in sudo permissions /etc/sudoers.d/SAPHanaSR file :

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#id-1.10.11.6

The `*` in this section could be changed to something more specific.

```
Cmnd_Alias HOOK_HELPER  = /usr/sbin/SAPHanaSR-hookHelper *
```

e.g. (not sure this covers all the cases, but it looks like fromt he current code)

```
Cmnd_Alias HOOK_HELPER  = /usr/sbin/SAPHanaSR-hookHelper --case checkTakeover --sid=${SID}
```

**Comment by chabowski** [comment]
@fmherschel @lpinne could you please check with Eike? Thank you!

**Comment by lpinne** [comment]
Hi yeoldegrove, hi chabowski,

thank you for this suggestion!

We might change from
---
Cmnd_Alias HOOK_HELPER  = /usr/sbin/SAPHanaSR-hookHelper *
---
to
---
Cmnd_Alias HOOK_HELPER  = /usr/sbin/SAPHanaSR-hookHelper --case checkTakeover --sid=<sid>
---
That <sid> is consistent with the other example.

Regards,
Lars

**Comment by chabowski** [comment]
Hi @lpinne thanks for fixing this! Closing the issue now.
