### ISSUE TITLE
[doc] Example 25:  Entry in sudo permissions /etc/sudoers.d/SAPHanaSR file 

### ISSUE THREAD

**Issue by yeoldegrove** [SUSE/suse-best-practices#319]
Example 25:  Entry in sudo permissions /etc/sudoers.d/SAPHanaSR file :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/index.html#id-1.10.7.5

Similar as in #315 we could add some more restrictive sudo permissions here (avoiding `*`).
There is already a TODO hint to the manpage, but https://github.com/SUSE/SAPHanaSR-ScaleOut/blob/71065cc84467eb715f8f1bd200e2f9d39afa2d0a/SAPHana/man/SAPHanaSrMultiTarget.py.7#L104-L116 also does not include more restrictive examples.

One could e.g. use this to cover all (non-)multi-target setups:
```
# SAPHanaSR-ScaleOut needs for /usr/share/SAPHanaSR-ScaleOut/SAPHanaSrMultiTarget.py
Cmnd_Alias GSH_QUERY      = /usr/sbin/crm_attribute -n hana_prd_gsh -G
Cmnd_Alias GSH_UPDATE     = /usr/sbin/crm_attribute -n hana_prd_gsh -v 2.2 -l reboot
# be compatible with non-multi-target mode
Cmnd_Alias SOK_GLOB       = /usr/sbin/crm_attribute -n hana_prd_glob_srHook -v SOK -t crm_config -s SAPHanaSR
Cmnd_Alias SFAIL_GLOB     = /usr/sbin/crm_attribute -n hana_prd_glob_srHook -v SOK -t crm_config -s SAPHanaSR
# be compatible with multi-target mode
Cmnd_Alias SOK_GLOB_MTS   = /usr/sbin/crm_attribute -n hana_prd_glob_mts -v SOK -t crm_config -s SAPHanaSR
Cmnd_Alias SFAIL_GLOB_MTS = /usr/sbin/crm_attribute -n hana_prd_glob_mts -v SOK -t crm_config -s SAPHanaSR
Cmnd_Alias SOK_SITEA      = /usr/sbin/crm_attribute -n hana_prd_site_srHook_Site1 -v SOK   -t crm_config -s SAPHanaSR
Cmnd_Alias SFAIL_SITEA    = /usr/sbin/crm_attribute -n hana_prd_site_srHook_Site1 -v SFAIL -t crm_config -s SAPHanaSR
Cmnd_Alias SOK_SITEB      = /usr/sbin/crm_attribute -n hana_prd_site_srHook_Site2 -v SOK   -t crm_config -s SAPHanaSR
Cmnd_Alias SFAIL_SITEB    = /usr/sbin/crm_attribute -n hana_prd_site_srHook_Site2 -v SFAIL -t crm_config -s SAPHanaSR
prdadm ALL=(ALL) NOPASSWD: GSH_QUERY, GSH_UPDATE, SOK_GLOB, SFAIL_GLOB, SOK_GLOB_MTS, SFAIL_GLOB_MTS, SOK_SITEA, SFAIL_SITEA, SOK_SITEB, SFAIL_SITEB
```

One noteworthy point would be that a `grep "^srHookGen = " /usr/share/SAPHanaSR-ScaleOut/SAPHanaSrMultiTarget.py` is needed to get the version needed for the "gsh" rule.

**Comment by chabowski** [comment]
@lpinne @fmherschel Hi Lars and Fabian - please see another enhancement proposal from Eike. Please let me know if you will implement the suggestion with one of the next updates, and if so, when it is done. Thanks very much.

**Comment by lpinne** [comment]
see https://github.com/SUSE/suse-best-practices/commit/8b0e8431e1e57ea490409ab701a252100205bc39

thanks for your input!
