### ISSUE TITLE
[doc] 6.1.2  How to move ASCS

### ISSUE THREAD

**Issue by andreas-mach** [SUSE/suse-best-practices#320]
6.1.2  How to move ASCS:

https://documentation.suse.com/sbp/all/html/SAP_NW740_SLE12_SetupGuide/index.html#id-how-to-move-ascs

What is the useage of this section, should this describe how to move **all** cluster resources away from a node?

As customer mentioned:

Using only the sapcontrol command "sapcontrol -nr 00 -function HAFailoverToNode """ will move ASCS instance to the other node in a two node cluster, as of the colocation constraint the ERS instance will be started on this node, also other active cluster resource like "SBD" will stay active on the node.

**Comment by fmherschel** [comment]
It is intended that the above command only moves the effected SAP instance. This also part of the SAP HA certification.
This method is not intended to be a migrate all resources away. It's the move of *the* central component which is most critical and this is now even possible with an SAP command (sapcontrol).  I tend to close this issue.

**Comment by fmherschel** [comment]
Hope my explanation is sufficient, closing the issue.
