### ISSUE TITLE
[doc] 

### ISSUE THREAD

**Issue by fmherschel** [SUSE/suse-best-practices#323]
https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-checking-the-corosync-configuration

Example for SBD_Setting has multiple errors:

a) SBD_WATCHDOG_TIMEOUT=5 (but text above says 15)
b) SBD_DELAY_START=yes -> this forces nodes to be fenced, if coming to late during a complete cluster start

**Comment by lpinne** [comment]
fixed by PR #377
