### ISSUE TITLE
Implementing the Python Hook SAPHanaSR Clarification 

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/suse-best-practices#324]
Hi @lpinne 

Maybe the "optionally" part  needs to be adjusted to align with SUSE best practice - or at least point out the pitfalls (which are sensible).

https://github.com/SUSE/suse-best-practices/edit/main/adoc/SLES4SAP-hana-sr-guide-PerfOpt-12.adoc
```
=== Implementing the Python Hook SAPHanaSR

This step must be done on both sites. {SAPHANA} must be stopped to change the
global.ini and allow {SAPHANA} to integrate the HA/DR hook script during start.

- Install the HA/DR hook script into a read/writable directory
- Integrate the hook into global.ini ({saphana} needs to be stopped for doing that offline)
- Check integration of the hook during start-up

Use the hook from the SAPHanaSR package (available since version 0.153). Optionally copy it to your preferred
directory like /hana/share/myHooks. The hook must be available on all SAP HANA cluster nodes.
```

Best regards,
Ab

**Comment by chabowski** [comment]
@lpinne is this solved? Can we close the issue?

**Comment by lpinne** [comment]
Hi Meike,

that was for backward compatibility. I do not expect new installations doing that way.
I wil remove "Optionally copy it to your preferred directory like /hana/share/myHook". 
PR will come in the next weeks.

Regards,
Lars

**Comment by lpinne** [comment]
Hi Meike,

I checked that guide. The mentioned sentence is not in there.
You can close this issue.

Regards,
Lars

**Comment by chabowski** [comment]
Thank you Lars - closing the issue now :-). Kind regards - Meike
