### ISSUE TITLE
[doc]  SAP HANA System Replication Scale-Up in the Cluster - performance optimized chain 

### ISSUE THREAD

**Issue by PeterPitterling** [SUSE/suse-best-practices#335]
SAP HANA System Replication Scale-Up in the Cluster - performance optimized chain :

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#id-1.3.2.7.5.3.2
https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-1.3.2.7.5.3.4

Third node should be called "SAP HANA tertiary"?

**Comment by chabowski** [comment]
@lpinne @fmherschel would you mind having a look? It is in the two graphics. Do you have several "secondary nodes" or a "primary, secondary, tertiary node" here? Thank you!

**Comment by fmherschel** [comment]
@PeterPitterling is "SAP HANA tertiary" now an official SAP terminology. As far as we have discussed in the SAP HANA HA board and as far as I could remember that is NOT the case and the SAP API names them all "secondaries".
So this is not our (SUSE) decision.

**Comment by fmherschel** [comment]
In SAP HANA SR there is only a primary and a secondary role implemented.

**Comment by chabowski** [comment]
Thank you @fmherschel ! I think it was exactly this question that needed to be clarified: in an SAP HANA environment, the term is "secondary" in general.

**Comment by fmherschel** [comment]
Hope it's OK to close the issue.
