### ISSUE TITLE
[doc]  Setting up SAP HANA HA/DR providers

### ISSUE THREAD

**Issue by varkoly** [SUSE/suse-best-practices#339]
Setting up SAP HANA HA/DR providers:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#cha.s4s.hana-hook

`SAP HANA must be stopped to change the global.ini and allow SAP HANA to integrate the HA/DR hook scripts during start. Alternatively, SAPHanaSR-manageProfile might be used for adapting the global.ini. See manual page SAPHanaSR-manageProfile(8) for details.`

There is no script **SAPHanaSR-manageProfile**. The script is called **SAPHanaSR-manageProvider**

**Comment by fmherschel** [comment]
@varkoly Tahnks!

**Comment by fmherschel** [comment]
Solved in PR #340.

**Comment by fmherschel** [comment]
DONE.
