### ISSUE TITLE
[doc]  Disabling systemd services of the ASCS and the ERS SAP instance

### ISSUE THREAD

**Issue by fmherschel** [SUSE/suse-best-practices#345]
Disabling systemd services of the ASCS and the ERS SAP instance:

https://documentation.suse.com/sbp/sap/single-html/SAP-S4HA10-setupguide-simplemount-sle15/#id-disabling-systemd-services-of-the-ascs-and-the-ers-sap-instance
> SAPEN2_10.service disabled
> SAPEN2_10.service disabled

Should be

> SAPEN2_00.service disabled
> SAPEN2_10.service disabled

**Comment by lpinne** [comment]
fixed by PR #377
