### ISSUE TITLE
[doc] Issue in "Check the load of the hook scripts"

### ISSUE THREAD

**Issue by roseswe** [SUSE/suse-best-practices#351]
Check the load of the hook scripts:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-check-the-load-of-the-hook-scripts

-----
What is the expected output for a correct installation and the output for e.g. a wrong or failed installation?

**Comment by fmherschel** [comment]
It quite trivial in that case. You either get a message that it *is* loaded or you get an error message. We could list them all.

**Comment by fmherschel** [comment]
Have you checked the man pages?

**Comment by lpinne** [comment]
Hi Ralph,

the manual pages SAPHanaSR-hookHelper(8) and SAPHanaSR.py(7) contain examples for checking whether hook and helper script are working.

We may not duplicate the manual pages within the setup guides.
However, for customer´s conveniance we are point to relervant manual pages at certain points in the guide, and we provide a list of relevant manual pages in the appendix.

Regards,
Lars
