### ISSUE TITLE
[doc] Issue in "Check if the SAP hostagent is installed on all cluster nodes"

### ISSUE THREAD

**Issue by lpinne** [SUSE/suse-best-practices#355]
Hi,

this section contains a monint typo:
https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-costopt-15/#id-check-if-the-sap-hostagent-is-installed-on-all-cluster-nodes
---
.../saphostctrl function ListInstances
= should be =>
.../saphostctrl -function ListInstances
---
There needs to be a dash "-" in front of string "function".

Regards,
Lars

**Comment by chabowski** [comment]
Fixed with PR#362. Closing. Thanks very much!
