### ISSUE TITLE
[doc] Issue in "Checking if the SAP hostagent is installed on all cluster nodes"

### ISSUE THREAD

**Issue by lpinne** [SUSE/suse-best-practices#356]
Hi,

there is a minot typo in section
https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-checking-if-the-sap-hostagent-is-installed-on-all-cluster-nodes
---
.../saphostcrl function ...
== should be =>
.../saphostctr -function ...
---
There needs to be a dash "-" in front of string "function".
Since the cost-opt guide shows the same typo, it might be wise to check all setup guides
for this. The dash seems to be in the adoc source.

Regards,
Lars

**Comment by chabowski** [comment]
Fixed with PR#362. Closing. Thanks very much!
