### ISSUE TITLE
[doc] Issue in "SAP HANA System Replication Scale-Up - Performance Optimized Scenario": Bad formatting

### ISSUE THREAD

**Issue by ajaeger** [SUSE/suse-best-practices#363]
SAP HANA System Replication Scale-Up - Performance Optimized Scenario:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#

Please read the introduction and check that the word "Disclaimer" is part of the intro without any whitespace. I propose to add a new paragraph here to separate disclaimer from the introduction.

Btw. This problem exists for all of the suse-best-practices guide.

**Comment by ajaeger** [comment]
I mean the very first paragraph, just search for "Dislaimer". I guess it's more the summary not the introduction.

**Comment by tomschr** [comment]
This is something that was already fixed in [openSUSE/suse-xsl#bd63489](https://github.com/openSUSE/suse-xsl/commit/bd63489a1c07999d7975fa018bfab11e43487358).
