### ISSUE TITLE
[doc] issue in sudoers example entry

### ISSUE THREAD

**Issue by ksanjeet** [SUSE/suse-best-practices#364]
In  EXAMPLE 18: ENTRY IN SUDO PERMISSIONS /ETC/SUDOERS.D/SAPHANASR FILE [#](https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-1.10.15.5)

following line is incorrect:
Cmnd_Alias HOOK_HELPER  = /usr/sbin/SAPHanaSR-hookHelper --case=checkTakeOver --sid=<sid>

It should be:
Cmnd_Alias HOOK_HELPER  = /usr/sbin/SAPHanaSR-hookHelper --sid=<SID> --case=checkTakeOver 

Overall there are 2 changes needed:
1) The SID has to be in uppercase
2) The order has to changed, i.e. first the --sid and then the --case.

REASON: the [susTkOver](https://github.com/SUSE/SAPHanaSR/blob/master/srHook/susTkOver.py#L78) hook script runs above command and if it doesn't exactly matches the sudoers entry then it will not get the required sudo permission.

**Comment by chabowski** [comment]
@fmherschel @lpinne could you please have a quick look and confirm? Thanks very much!

**Comment by lpinne** [comment]
Hi Meike,

I will fix the example.
PR will come in the next weeks.

Regards,
Lars

**Comment by lpinne** [comment]
https://github.com/SUSE/suse-best-practices/pull/367

**Comment by ksanjeet** [comment]
The proposed line
Cmnd_Alias HOOK_HELPER = /usr/sbin/SAPHanaSR-hookHelper --sid=<SID> --case=checkTakeOver
is now implemented, however it has one mistake: The alphabet "o" in "checkTakeOver" should be lowercase.
I have created a new [issue](https://github.com/SUSE/suse-best-practices/issues/368) for this.
