### ISSUE TITLE
[doc] Issue in "ENTRY IN SUDO PERMISSIONS /ETC/SUDOERS.D/SAPHANASR FILE"

### ISSUE THREAD

**Issue by ksanjeet** [SUSE/suse-best-practices#368]
ENTRY IN SUDO PERMISSIONS /ETC/SUDOERS.D/SAPHANASR FILE:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-1.10.15.5

In the example 18 the line

Cmnd_Alias HOOK_HELPER  = /usr/sbin/SAPHanaSR-hookHelper --sid=<SID> --case=checkTakeOver

should be

Cmnd_Alias HOOK_HELPER  = /usr/sbin/SAPHanaSR-hookHelper --sid=<SID> --case=checkTakeover

over in Takeover should have a lowercase "o".

**Comment by lpinne** [comment]
fixed in adoc source
