### ISSUE TITLE
[doc] Issue in "SIMPLE BACKUP FOR THE SYSTEM DATABASE AND ALL TENANTS WITH ONE SINGLE BACKUP CALL"

### ISSUE THREAD

**Issue by varkoly** [SUSE/suse-best-practices#374]
SIMPLE BACKUP FOR THE SYSTEM DATABASE AND ALL TENANTS WITH ONE SINGLE BACKUP CALL:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-costopt-15/index.html#id-1.9.6.3

~> hdbsql -u SYSTEM -d SYSTEMDB -i 10 \
   "BACKUP DATA FOR FULL SYSTEM USING FILE ('backup')"

should be replaced by:
~> hdbsql -u SYSTEM -d SYSTEMDB -i \<instanceNumber\> \
   "BACKUP DATA FOR FULL SYSTEM USING FILE ('backup')"

**Comment by fmherschel** [comment]
![image](https://user-images.githubusercontent.com/1759921/232840810-a8b5c698-a25c-4292-b822-e1c023cb6448.png)
 ??

**Comment by varkoly** [comment]
You schould not remove it. But you sould use the place holder \<instanceNumber\> as on other places. It is very confusing when sometimes a number stands there sometimes the placeholder.

**Comment by varkoly** [comment]
clarified
