### ISSUE TITLE
[doc] Issue in "The concept of the cost optimized scenario"

### ISSUE THREAD

**Issue by varkoly** [SUSE/suse-best-practices#375]
The concept of the cost optimized scenario:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-costopt-15/index.html#id-the-concept-of-the-cost-optimized-scenario

The link in text is bad. There is nothing with the mentioned topic. ("Using Secondary Servers for Non-Productive systems".)

In addition to the description of the concept in this best practice document, read the corresponding SAP documentation such as "Using Secondary Servers for Non-Productive systems". The section is available for example for SAP HANA 2.0 SPS05 at https://help.sap.com/viewer/6b94445c94ae495c83a19646e7c3fd56/2.0.05/en-US/5447545b91a04cf8a0d6133a026f2be5.html.

I've found this blog entry which can replace it: 
https://blogs.sap.com/2021/10/19/reuse-secondary-hardware-for-non-productive-sap-hana-systems-with-sap-hana-system-replication/

**Comment by lpinne** [comment]
looks like we can cloese this one
