### ISSUE TITLE
[doc] Issue in "Setting up the initial cluster using ha-cluster-init"

### ISSUE THREAD

**Issue by jirib** [SUSE/suse-best-practices#381]
Setting up the initial cluster using ha-cluster-init:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-costopt-15/#id-setting-up-the-initial-cluster-using-ha-cluster-init

IIUC ha-cluster-init is deprecated, `crmsh` should be used instead.

**Comment by lpinne** [comment]
Hi jirib,
the setup guides have been created a while ago. At that time there was only ha-cluster-init. 
Customers expect SUSE to provide ha-cluster-init for the whole lifetime of SLE 15, and in many cases have used ha-cluster-init for own automation. So ha-cluster-init should work on SLE 15 until 2037 or so.
For the next generation of setup guides we will use whatever will be approproate then, e.g. crm. 
Regards,
Lars
