### ISSUE TITLE
[doc] Issue in "MOUNT NFS SHARES ON ALL NON-HANA NODES"

### ISSUE THREAD

**Issue by ksanjeet** [SUSE/suse-best-practices#386]
MOUNT NFS SHARES ON ALL NON-HANA NODES:

https://documentation.suse.com/sbp/sap/single-html/SAP-S4HA10-setupguide-simplemount-sle15/#id-1.6.14.5

In the two below commands that should make fstab entries for NFS mountpoints, the filesystem option(4th field) is missing. For example the 4th field should have been "defaults".

So, we may make a change 

FROM:

echo "192.168.1.1:/data/export/S4_HA_CLU_10/EN2/sapmnt/EN2 /sapmnt/EN2 nfs 0 0" >> /etc/fstab
echo "192.168.1.1:/data/export/S4_HA_CLU_10/EN2/usr/sap/EN2 /usr/sap/EN2 nfs 0 0" >> /etc/fstab

TO:

echo "192.168.1.1:/data/export/S4_HA_CLU_10/EN2/sapmnt/EN2 /sapmnt/EN2 nfs defaults 0 0" >> /etc/fstab
echo "192.168.1.1:/data/export/S4_HA_CLU_10/EN2/usr/sap/EN2 /usr/sap/EN2 nfs defaults 0 0" >> /etc/fstab

**Comment by lpinne** [comment]
Thanks a lot!
I will fix it.

**Comment by lpinne** [comment]
https://github.com/SUSE/suse-best-practices/pull/387
