### ISSUE TITLE
[doc] Issue in "SAP NetWeaver Enqueue Replication 1 High Availability Cluster - SAP NetWeaver 7.40 and 7.50"

### ISSUE THREAD

**Issue by chabowski** [SUSE/suse-best-practices#391]
Hi @fmherschel and @lpinne 

I was made aware of Jira ticket request 
[https://jira.suse.com/browse/PED-2080]
(https://jira.suse.com/browse/PED-2080)

and I was told that it also impacts two of your SBP documents. This is one (I will open an issue for the other document, too): 

SAP NetWeaver Enqueue Replication 1 High Availability Cluster - SAP NetWeaver 7.40 and 7.50:
[https://documentation.suse.com/sbp/all/html/SAP-nw740-sle15-setupguide/index.html#]
https://documentation.suse.com/sbp/all/html/SAP-nw740-sle15-setupguide/index.html#

Can you please have a look at the Jira ticket/request and decide if or how to implement it? 

Thank you very much!
Meike

**Comment by fmherschel** [comment]
@chabowski Most likely I will not be able to work on this issue before end of September.

**Comment by chabowski** [comment]
Solved with PR:
https://github.com/SUSE/suse-best-practices/pull/393
