### ISSUE TITLE
[doc] Issue in "SAP S/4 HANA - Enqueue Replication 2 High Availability Cluster"

### ISSUE THREAD

**Issue by chabowski** [SUSE/suse-best-practices#392]
Hi @fmherschel and @lpinne 

I was made aware of Jira ticket request 
[https://jira.suse.com/browse/PED-2080]
(https://jira.suse.com/browse/PED-2080)

and I was told that it also impacts two of your SBP documents. This is the other (I have opened an extra issue for the first document, too): 

SAP S/4 HANA - Enqueue Replication 2 High Availability Cluster:
[https://documentation.suse.com/sbp/all/html/SAP-S4HA10-setupguide-sle15/index.html#]
https://documentation.suse.com/sbp/all/html/SAP-S4HA10-setupguide-sle15/index.html#

Can you please have a look at the Jira ticket/request and decide if or how to implement it? 

Thank you very much!
Meike

**Comment by lpinne** [comment]
Hi,
I have commented in the jira ticket: Once specific settings have been documented for each cloud and storage backend, we  can point to that in our generic SUSE setup guides. 
Regards,
Lars

**Comment by chabowski** [comment]
Can we close issues #391 and #392 ? Thanks!

**Comment by chabowski** [comment]
Solved with PR:
https://github.com/SUSE/suse-best-practices/pull/393
