### ISSUE TITLE
[doc] Issue in "ADDITIONALLY TO THE NFS SHARES: ALL CLUSTER NODES NEED TO HAVE ACCESS TO THE SBD BLOCK DEVICES"

### ISSUE THREAD

**Issue by markrgordon** [SUSE/suse-best-practices#399]
ADDITIONALLY TO THE NFS SHARES: ALL CLUSTER NODES NEED TO HAVE ACCESS TO THE SBD BLOCK DEVICES:

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/#id-1.6.6.12

requirements list specifies one SBD.   But below the list it specifies (and shows in diagram) three SBDs.

**Comment by chabowski** [comment]
@lpinne @fmherschel would you mind having a look? Thank you!

**Comment by lpinne** [comment]
Hi markrgordon,

with disk-based SBD stonith, at least one SBD disk is required. Three are recommended.
Therefor the section says:
---
Requirements with 5 SAP HANA instances per site (3+2 : 3+2) - with a majority maker:

    10 VMs with each 32 GB RAM, 50 GB disk space

    1 VM with 2 GB RAM, 50 GB disk space

    1 shared disk for SBD with 10 MB disk space

    2 NFS pools (one per site) with a capacity of each 132 GB

    1 additional IP address for takeover

The SBD based fencing needs up to 3 shared block devices.
---
Consequently, the parameter sheets says:
---
SBD STONITH block device(s)
---
And later on the setup section says:
---
SBD (at least one device)
...
For SBD based fencing you can use one up to three SBD devices. 
---

Regards,
Lars
