### ISSUE TITLE
[doc] Issue in "Cluster bootstrap and more"

### ISSUE THREAD

**Issue by varkoly** [SUSE/suse-best-practices#403]
Cluster bootstrap and more:

https://documentation.suse.com/sbp/sap-15/single-html/SLES4SAP-hana-sr-guide-costopt-15/#id-cluster-bootstrap-and-more

1. In ' property cib-bootstrap-options:' the entry 'stonith-enabled="true" \' is superfluous in 2 node configuration
2. In 'property cib-bootstrap-options:' missing the entry ' priority-fencing-delay="30"

( You can compare with https://documentation.suse.com/sbp/sap-15/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-cluster-bootstrap-and-more )

**Comment by lpinne** [comment]
has been discussed offline
