### ISSUE TITLE
[doc] Issue in "Constraints"

### ISSUE THREAD

**Issue by ksanjeet** [SUSE/suse-best-practices#408]
Constraints:

https://documentation.suse.com/sbp/sap-15/html/SLES4SAP-hana-scaleout-multitarget-perfopt-15/index.html#id-constraints

In the step "Load the file to the cluster."

The command mentioned is 
"configure load update crm-cs.txt"

Whereas it should be
"crm configure load update crm-cs.txt"

**Comment by fmherschel** [comment]
Fixed in PR #409

**Comment by chabowski** [comment]
This is fixed and will be published with the next public build of the repo. Thanks very much!
