### ISSUE TITLE
[doc] Issue in "ENTRY IN SUDO PERMISSIONS /ETC/SUDOERS.D/SAPHANASR FILE"

### ISSUE THREAD

**Issue by ksanjeet** [SUSE/suse-best-practices#410]
ENTRY IN SUDO PERMISSIONS /ETC/SUDOERS.D/SAPHANASR FILE:

https://documentation.suse.com/sbp/sap-15/html/SLES4SAP-hana-scaleout-multitarget-perfopt-15/index.html#id-1.10.12.4

In the example sudoers entry for susTakeover hook the SID should be in uppercase. I suggest we change the sudoer entry
from:
`<sid>adm ALL=(ALL) NOPASSWD: /usr/sbin/SAPHanaSR-hookHelper --sid=<sid> *`
to:
`<sid>adm ALL=(ALL) NOPASSWD: /usr/sbin/SAPHanaSR-hookHelper --sid=<SID> *`

When I tested with lowercase sid then takeover is blocked with RC=1. With uppercase SID takeover is permitted.

**Comment by chabowski** [comment]
@lpinne @fmherschel would you mind having a look, please? Thank you!

**Comment by lpinne** [comment]
Hi,
the guide will be updated per pull request #411. 
Thanks for reporting this issue!
Regards,
Lars
