### ISSUE TITLE
SLES12-4-SAP recommended documentation change of use of SAPHanaSrMultiTarget.py versus SAPHanaSr

### ISSUE THREAD

**Issue by chabowski** [SUSE/suse-best-practices#412]
(issue found by Nickolas Younker)

SLES12-4-SAP recommended documentation change of use of SAPHanaSrMultiTarget.py versus SAPHanaSr
https://documentation.suse.com/sbp/sap-12/html/SLES4SAP-hana-scaleOut-PerfOpt-12/index.html#id-1.10.6.7

SAP HANA 2.0 SPS04 or later provides the HA/DR provider hook method srConnectionChanged() with needed parameters for SAPHanaSrMultiTarget.py.

Specifically: Old SR hook ha_dr_provider_SAPHanaSR listed where the new SAPHanaSrMultitarget should be used FROM
```
===============
[ha_dr_provider_SAPHanaSR]
provider = SAPHanaSR
path = /usr/share/SAPHanaSR-ScaleOut
execution_order = 1

[trace]
ha_dr_saphanasr = info
===============
```
TO
```
===============
[ha_dr_provider_saphanasrmultitarget]
provider = SAPHanaSrMultiTarget
path = /usr/share/SAPHanaSR-ScaleOut/
execution_order = 1

[trace]
ha_dr_saphanasrmultitarget = info
===============
```

See https://bugzilla.suse.com/show_bug.cgi?id=1218901
See correct documentation for SLES15
https://documentation.suse.com/sbp/sap-15/html/SLES4SAP-hana-scaleOut-PerfOpt-15/index.html#id-1.10.7.5

**Comment by chabowski** [comment]
@lpinne @fmherschel would you mind having a look? Thank you!

**Comment by lpinne** [comment]
Hi Nickolas, hi Meike,

1) As Fabian wrote, updating the hook script needs some preparation and steps. The procedure is outlined in manual page SAPHanaSR-hookHelper(8) and blog articles on #towardszeordowntime. That update procedure is needed if a running HANA should be changed to multi-target.
2) Changing the SLE 12 setup guide to the new hook script is out of scope. The SLE 12 guides are kept as is, just for reference. New deployments should be done on SLE 15. This is a matter of priorities vs. resources.
3) However, if a customer wants to deploy new HANAs scale-out multi-target on SLE 12 they could do. If they feel unsure how to do that, they might as for SUSE services.

I am sorry for not replying a plain "will do".

Regards,
Lars

**Comment by fmherschel** [comment]
@chabowski Based on feedback by @lpinne and @fmherschel this looks like a wont-fix. If we really decide that we must fix that we need to create a project based on that issue.

**Comment by chabowski** [comment]
Thank you both @fmherschel and @lpinne for the immediate resonse. I tagged the issue as "wontfix" for now and will close it.

**Comment by chabowski** [comment]
wontfix for now
