### ISSUE TITLE
[doc] Issue in "Allowing <sid>adm to access the cluster"

### ISSUE THREAD

**Issue by ksanjeet** [SUSE/suse-best-practices#413]
Allowing <sid>adm to access the cluster:

https://documentation.suse.com/sbp/sap-15/html/SLES4SAP-hana-scaleout-multitarget-perfopt-15/index.html#id-allowing-sidadm-to-access-the-cluster

In order to set the new multi target related attribute "hana_<sid>_glob_mts", we will need to allow permission in the sudoers entry and hence, following change is suggested:

from:
====
`# SAPHanaSR-ScaleOut needs for HA/DR hook scripts`
`<sid>adm ALL=(ALL) NOPASSWD: /usr/sbin/crm_attribute -n hana_<sid>_site_srHook_*`
`<sid>adm ALL=(ALL) NOPASSWD: /usr/sbin/crm_attribute -n hana_<sid>_gsh *`
`<sid>adm ALL=(ALL) NOPASSWD: /usr/sbin/SAPHanaSR-hookHelper --sid=<SID> *`

to:
===
`# SAPHanaSR-ScaleOut needs for HA/DR hook scripts`
`<sid>adm ALL=(ALL) NOPASSWD: /usr/sbin/crm_attribute -n hana_<sid>_site_srHook_*`
`<sid>adm ALL=(ALL) NOPASSWD: /usr/sbin/crm_attribute -n hana_<sid>_gsh *`
`<sid>adm ALL=(ALL) NOPASSWD: /usr/sbin/crm_attribute -n hana_<sid>_glob_mts *`
`<sid>adm ALL=(ALL) NOPASSWD: /usr/sbin/SAPHanaSR-hookHelper --sid=<SID> *`

**Comment by chabowski** [comment]
@ksanjeet @fmherschel @lpinne are you planning to update the document sometime soon? Thank you!

**Comment by chabowski** [comment]
Thank you, merging and closing PR.
