### ISSUE TITLE
[doc] Issue in "Microsoft SQL Server on SUSE Linux Enterprise Server" - out of date

### ISSUE THREAD

**Issue by tlssuse** [SUSE/suse-best-practices#414]
Microsoft SQL Server on SUSE Linux Enterprise Server:

https://documentation.suse.com/sbp/server-linux/html/TRD-sql-server-getting-started/index.html#

This documentation is significantly out-of-date.
May we please archive this documentation to avoid confusion with the current, official documentation hosted by Microsoft (https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-suse?view=sql-server-linux-ver16&preserve-view=true)?

@chabowski : Is this something you can help facilitate?

**Comment by chabowski** [comment]
Done - document will be de-published with the next official repo build. Thank you @tlssuse for reporting the issue.
