### ISSUE TITLE
[doc] Issue in "Example cluster configuration"

### ISSUE THREAD

**Issue by emilianolangella** [SUSE/suse-best-practices#421]
Example cluster configuration:

https://documentation.suse.com/sbp/sap-15/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#id-example-cluster-configuration

We should suggest to use "Optional" and not "2000" when configuring the order as we already did here in the same guide:
https://documentation.suse.com/sbp/sap-15/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#id-constraints-for-saphanasr

```
order ord_SAPHana_HA1_HDB10 Optional: cln_SAPHanaTopology_HA1_HDB10 \
    msl_SAPHana_HA1_HDB10
```

**Comment by lpinne** [comment]
Hi Emiliano,
should be fixed by
https://github.com/SUSE/suse-best-practices/pull/420
Thanks!
Regards,
Lars

**Comment by chabowski** [comment]
Thank you! Fixed, and PR is merged. Change will be published with the next build of the repo.
