### ISSUE TITLE
[doc] Issue in "Example Cluster Configuration"

### ISSUE THREAD

**Issue by emilianolangella** [SUSE/suse-best-practices#422]
Example Cluster Configuration:

https://documentation.suse.com/sbp/sap-12/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#id-example-cluster-configuration

We should suggest to use "Optional" and not "2000" when configuring the order as we already did here in the same guide:
https://documentation.suse.com/sbp/sap-12/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#id-constraints

`order ord_SAPHana_HA1_HDB10 Optional: cln_SAPHanaTopology_HA1_HDB10 \
    msl_SAPHana_HA1_HDB10`

**Comment by fmherschel** [comment]
@emilianolangella Good catch.

**Comment by fmherschel** [comment]
The https://documentation.suse.com/sbp/sap-12/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#id-example-cluster-configuration is more for a reference the important one is https://documentation.suse.com/sbp/sap-12/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#id-constraints. It seams we missed to apply a fix to the entire configuration example.

**Comment by emilianolangella** [comment]
I opened #423.

**Comment by chabowski** [comment]
Thank you! PR is merged, change will be published with the next repo build.
