### ISSUE TITLE
[doc] Issue in "Client image configuration recommendations"

### ISSUE THREAD

**Issue by dogeevarghese** [SUSE/suse-best-practices#428]
Client image configuration recommendations:

https://documentation.suse.com/sbp/cloud-computing/html/SBP-CSP-UpdateInfra/index.html#sec-client-image-conf-recommendations

Below line needs correction as the .pem certificate path is incorrect under 7.1 Client image configuration recommendations

> The public key files for all Region Servers generated with the genRegionServerCert command. Files must be in pem format and end with the .pem extension. Further the names must match the names set in the configuration file. The files need to be placed in the `/var/lib/regionService/certs/` directory. ". 

**Additional details**

Looking at the default config file, I see certLocation is NOT `/var/lib/regionService/certs/` as described in the doc. Path prefix is /usr not /var.

```
cat /etc/regionserverclnt.cfg 
[server]
api = regionInfo
certLocation = /usr/lib/regionService/certs
regionsrv = COMMA_SEP_LIST_OF_CLOUD_SPECIFIC_REGION_SERVER
metadata_server = OPTIONAL_URL_FOR_METADATA_SERVER_SMT_INFO
```

and the logs reported missing file at the desired location.

```
INFO:Using API: regionInfo
INFO:Getting update server information, attempt 1
INFO:	Using region server: dc2region.dc2.lan
INFO:	No cert found: /usr/lib/regionService/certs/dc2region.dc2.lan.pem skip this server
INFO:Waiting 20 seconds before next attempt
INFO:Getting update server information, attempt 2
INFO:	Using region server: dc2region.dc2.lan
INFO:	No cert found: /usr/lib/regionService/certs/dc2region.dc2.lan.pem skip this server
INFO:Waiting 10 seconds before next attempt
INFO:Getting update server information, attempt 3
INFO:	Using region server: dc2region.dc2.lan
INFO:	No cert found: /usr/lib/regionService/certs/dc2region.dc2.lan.pem skip this server
ERROR:Request not answered by any server after 3 attempts
ERROR:Exiting without registration
```

However, no such error found after I copied  .pem file at `/usr/lib/regionService/certs/` and it started working.

Thanks,
Dominic Geevarghese
MSP Solution Architect

**Comment by chabowski** [comment]
done, fix will show up after the next repo build. Thanks!
