### ISSUE TITLE
[doc] Issue in "Deployment"

### ISSUE THREAD

**Issue by dogeevarghese** [SUSE/suse-best-practices#429]
Deployment:

https://documentation.suse.com/sbp/cloud-computing/html/SBP-CSP-UpdateInfra/index.html#sec-region-server-deploy

Under 6.2 Deployment, step number 6 is 

> Modify /etc/apache2/vhosts.d/regionsrv_vhost.conf. Change `SUBSTITUTE_WITH_CLOUD_SPECIFC_NAME `in 
> the `ServerName` option so that it matches the fully-qualified host name used in the genRegionServerCert.
> Change the following section so that it matches what is below.

```
 <Directory /srv/www/regionService>
                                                        WSGIProcessGroup regionInfo
                                                        WSGIApplicationGroup %{GLOBAL}
                                                        <RequireAll>
                                                                        Require all granted
                                                        </RequireAll>
                                                </Directory>
```

**Could you please fix below ?**

1) The snippet in the doc is not really referring `ServerName` parameter. So this needs to be replaced by the default code by 

```
Listen 443

<VirtualHost *:443>
    ServerName SUBSTITUTE_WITH_CLOUD_SPECIFC_NAME
    SSLEngine on
  
```

Here, consumer is expected to replace the text `SUBSTITUTE_WITH_CLOUD_SPECIFC_NAME` by a fully-qualified hostanme used in the genRegionServerCert command.

2) Please also adjust the line as the new snippet is default config & expecting consumer/customer to modify it accordingly.

> Change the following section so that it matches what is below.

Thanks,
Dominic Geevarghese
MSP Solution Architect

**Comment by chabowski** [comment]
done, changes will show up after the next repo build. Thanks!
