### ISSUE TITLE
[doc] Issue in "SAP HANA System Replication Scale-Out High Availability in Amazon Web Services"

### ISSUE THREAD

**Issue by rgentyala** [SUSE/suse-best-practices#434]
SAP HANA System Replication Scale-Out High Availability in Amazon Web Services:

https://documentation.suse.com/sbp/sap-12/html/SLES-SAP-hana-scaleOut-PerfOpt-12-AWS/index.html#

**Comment by chabowski** [comment]
Hi @rgentyala - which issue did you want to report? Thank you!

**Comment by rgentyala** [comment]
Please ignore that. I also updated Git.

Thank You and Best Regards,
RAJ KUMAR (RK) GENTYALA
Cloud Platform Technical Product Leader
SAP Solutions Architect. IBM Certified Consulting Expert
[A blue and purple circle with white text  Description automatically generated]Website: https://www.ibm.com/cloud/sap Phone: +1-925-319-7246<tel:+19253197246> (Cell) email: ***@***.******@***.***>    [signature_64350064] <http://linkedin.com/in/gentyala>
[signature_1233450445]
Next Vacation Dates



From: Meike Chabowski ***@***.***>
Date: Wednesday, June 12, 2024 at 9:29 AM
To: SUSE/suse-best-practices ***@***.***>
Cc: RAJ KUMAR (RK) GENTYALA ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [SUSE/suse-best-practices] [doc] Issue in "SAP HANA System Replication Scale-Out High Availability in Amazon Web Services" (Issue #434)
Hi @rgentyala - which issue did you want to report? Thank you! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <SUSE/suse-best-practices/issues/434/2163154073@ github. com>


Hi @rgentyala<https://github.com/rgentyala> - which issue did you want to report? Thank you!

**Comment by chabowski** [comment]
Thank you 😃
