### ISSUE TITLE
[doc] Issue in "Deploying the chart"

### ISSUE THREAD

**Issue by dmathern86** [SUSE/suse-best-practices#454]
Deploying the chart:

https://documentation.suse.com/sbp/sap-other/html/SAP-EIC/index.html#id-deploying-the-chart

There is a syntax error in the install application code block 
$ helm install metallb oci://dp.apps.rancher.io/charts/redis \
-f values.yaml \
--namespace=redis
--version

needs to be replace with 
$ helm install redis oci://dp.apps.rancher.io/charts/redis \
-f values.yaml \
--namespace=redis
--version

**Comment by chabowski** [comment]
This should be fixed with the next public build of the repo. Thanks for reporting1
