### ISSUE TITLE
[doc] Issue in "Installing the application"

### ISSUE THREAD

**Issue by dmathern86** [SUSE/suse-best-practices#455]
Installing the application:

https://documentation.suse.com/sbp/sap-other/html/SAP-EIC/index.html#id-installing-the-application-2

There is an error in the installation application code block:
$ helm install metallb oci://dp.apps.rancher.io/charts/postgres -f values.yaml --namespace=postgres

needs to be replaced with:
$ helm install postgres oci://dp.apps.rancher.io/charts/postgres -f values.yaml --namespace=postgres

**Comment by chabowski** [comment]
This should be fixed with the next public repo build. Thanks for reporting!
