### ISSUE TITLE
[doc] Issue in "CLUSTERED MACHINES TWO-NODE SCENARIO"

### ISSUE THREAD

**Issue by pirat013** [SUSE/suse-best-practices#464]
CLUSTERED MACHINES TWO-NODE SCENARIO:

https://documentation.suse.com/sbp/sap-15/html/SAP-S4HA10-setupguide-simplemount-sle15/index.html#id-1.6.9.6

I found a "vortual" host name, I guess it should be "virtual" :-)

**Comment by fmherschel** [comment]
Matching to the current fall and winter season it could also be "viral host name" ;-) 
Thanks for the catch :)

**Comment by fmherschel** [comment]
Already updated the adoc file in PR #465

**Comment by chabowski** [comment]
thanks @pirat013 for spotting this, and thanks @fmherschel for the immediate fix. Change will be online with the next public repo build.
