### ISSUE TITLE
[doc] Issue in "Preparing the operating system and installing the cluster softwaren"

### ISSUE THREAD

**Issue by pirat013** [SUSE/suse-best-practices#466]
Preparing the operating system and installing the cluster softwaren:

https://documentation.suse.com/sbp/sap-15/html/SAP-S4HA10-setupguide-sle15/index.html#id-preparing-the-operating-system-and-installing-the-cluster-softwaren

Good morning,
I found another one :-)
softwaren -> software

**Comment by chabowski** [comment]
@pirat013 thank you - fixed with the next repo build :-).
