### ISSUE TITLE
SAP HANA System Replication Scale-Up - Performance Optimized Scenario

### ISSUE THREAD

**Issue by pirat013** [SUSE/suse-best-practices#86]
The chapter Set Up SAP HANA HA/DR providers is incomplete, task 4 and 5 are missing in both guide for SLE12 and 15.

**Comment by fmherschel** [comment]
Hmm I thought I did explicitly wrote that part. Lets look in the sources once I have time to do that.
Thanks for the heads-up.

**Comment by chabowski** [comment]
@fmherschel Would you mind checking the sources on SBP master? Probably you forgot to do a PR after having updated the doc in your repo?

**Comment by chabowski** [comment]
Hi @pirat013 and @fmherschel, is this issue still open? 
Thanks - Meike

**Comment by fmherschel** [comment]
Yes unfortunately I had to focus on other projects and completely forgot to work on this issue. I still need to check, why these subsections disappeared. In the master they are really missing also in the sources (so no build-problem).

**Comment by fmherschel** [comment]
@chabowski : I like to label the issues such as "bug", "enhancement", "invalid". However in the area "labels" In just see "None yet" and I am not able to add labes to the issues. Could you please promote me so I could add them?

**Comment by fmherschel** [comment]
@chabowski : I have seen that you added assignees and labels to one of the other issues. However I am not allowed to do that by my owne :/

**Comment by chabowski** [comment]
Hmm - do you know how I can make you be able to add labels etc ??

**Comment by fmherschel** [comment]
I do not know how to change my permissions. Maybe one step back. How did you add the labels?
I tried the following:
1. Open the issue
2. At the right side there is a list of "facts" like "Assignees", "Labels", "Projects". In this project they are all grey for and I could not
change the contents of "Assegnees" and "Labels"
Maybe I do something wrong?

**Comment by fmherschel** [comment]
I can see your changes, but could not edit them.

**Comment by fmherschel** [comment]
In the project "https://github.com/SUSE/SAPHanaSR" the entries are also grey, but I have a "properties"-wheel (gear) at the most right side. This allows me to edit things. In this project I do not have these gears.

**Comment by chabowski** [comment]
@fmherschel I did the same and could add you and the other assignees and the labels. It is probably a matter of who might directly contribute to the repo?

**Comment by chabowski** [comment]
@fmherschel are you a member of the https://github.com/SUSE/SAPHanaSR repo, with admin or at least write access rights?

**Comment by chabowski** [comment]
@fmherschel can you check if it works now? I gave you write access to the repo.

**Comment by fmherschel** [comment]
@chabowski : Yes :) That looks good now!

**Comment by fmherschel** [comment]
@chabowski : Maybe "Triage" would also be enough:
https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

**Comment by chabowski** [comment]
@fmherschel in our org, we only have read, write, admin. But that is fine!

**Comment by fmherschel** [comment]
@chabowski : +1

**Comment by pirat013** [comment]
done
