### ISSUE TITLE
Problem with ADOC variables {ldquo} and {rdquo} PLUS problems with indentation of paragraphs/titles

### ISSUE THREAD

**Issue by fmherschel** [SUSE/suse-best-practices#9]
While I  was able to solve some document internal problems regarding variable replacement we still
have two variables referenced by common_gfdl1.2_i.adoc. The missing variables are: {ldquo} and {rdquo}.

**Comment by fmherschel** [comment]
In section "5.2 Installation" some paragraphs begin with a plus sign (+). In our adoc the plus has
been added, because we tell adoc to keep the indentation also after examples.

Also the titles of examples are damaged. And they begin with a plus sign and are formatted as paragraphs instead of titles.

Examples:
 "+ .The XML password template", "+ .Using hdblcm in batch mode" (Examples for damaged titles)
 "+ After having created the XML..."  (Example for damaged paragraph)

Best,
Fabian

**Comment by chabowski** [comment]
> While I was able to solve some document internal problems regarding variable replacement we still
> have two variables referenced by common_gfdl1.2_i.adoc. The missing variables are: {ldquo} and {rdquo}.

After discussing with Tom, we decided to replace these variables (which are indeed only quotation marks) with clear text, as variables are not really needed here.

**Comment by fmherschel** [comment]
+1

**Comment by fmherschel** [comment]
About the second topic - I only added the second topic, because github disallowed me to open an own issue for that (the apply button keeps gray):
Do you like me to send you (via mail) to screenshots of the "original" typesetting in our build and the
screenshot of the build document available online?

**Comment by chabowski** [comment]
Yes that might be helpful. I am still "investigating" - it most probably is a conversion bug but I don't know yet why.

**Comment by fmherschel** [comment]
send the screenshots via eMail

**Comment by chabowski** [comment]
Yes - got them, thank you Fabian! I am struggling to find the bug/issue - our build does it correctly in Example 7 but fails starting with Example 8 (which as far as I can see uses the same structure with the + like Example 7 ... ). But we will get there - I will ask Frank to have a look at it tomorrow morning ...

**Comment by chabowski** [comment]
@fmherschel: we found the issue, it was a simple formatting issue. The bullet list above the two examples that did not show up correctly is now in an open block, the example titles show up correctly and the examples also have the correct indentation now.

**Comment by fmherschel** [comment]
Are the changes for this issue and also the problem solution for ldquo/rdquo committed to the project? Currently I do not see the commit. I would like to rebase/refork the project to test a rebuild.

**Comment by chabowski** [comment]
commit 56374a873034c0729cee49b4eb174e5998424fd5 contains the solution for the format issue that caused the buggy display of the example titles. It also contains the fix of an outdated link, and replacement of abbreviation SLES with SUSE Linux Enterprise Server (there is a policy that there should not be product name abbreviations in plain text). I will give the paper another review tomorrow though before publication.

**Comment by fmherschel** [comment]
@chabowski: Did you have had a chance to review the paper and to publish it? Today I still got the old version from the sle12 docu page. Do you like to send us (Bernd and me) a build pdf just before publishing it?

**Comment by chabowski** [comment]
@fmherschel, @pirat013 
[SLES4SAP-hana-scaleOut-PerfOpt-12_color_en.pdf](https://github.com/SUSE/suse-best-practices/files/2586031/SLES4SAP-hana-scaleOut-PerfOpt-12_color_en.pdf)
 - hmm seems the latest version I sent was on Thurs evening - sorry I meant to send another one on Mon and was wondering why I didn't hear back. You should have a current version in your inbox, but I just built a new one - see attached.

**Comment by fmherschel** [comment]
I think we could close this issue right now.

**Comment by chabowski** [comment]
Sounds good - thank you :-)
