### ISSUE TITLE
[doc] Example&nbsp;12:  Adding SAPHanaSR via global.ini 

### ISSUE THREAD

**Issue by roseswe** [SUSE/suse-best-practices#95]
Example&nbsp;12:  Adding SAPHanaSR via global.ini :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-12/#id-1.9.6.6

On one node only or on all nodes? We should document this more in detail

**Comment by chabowski** [comment]
@fmherschel @lpinne @pirat013 
Ralph Roth has submitted several issues/questions  (via the "report a bug" link in the doc which opens a GitHub issue).
Can you please have a look? This is his second question/issue.
Thanks very much!

**Comment by fmherschel** [comment]
The *global.ini* is Global to an entire SAP HANA database (once) per site. As typically the global.ini is installed on NFS for Scale-Out it needs (of course) only to be changed once per site. This should be clear for SAP architects and is more a SAP specific question.
For scale-Up it needs to be done on both sides. We already explained that:
> This step must be done on both sites.

**Comment by roseswe** [comment]
As said I mirror only customer experience here

**Comment by fmherschel** [comment]
And left is at the left side ;-)

**Comment by lpinne** [comment]
@roseswe: Thanks for the hint. Even if global.ini should be known to SAP admins, I agree the mentioned example is a little unclear. We might add somthing like:
---
On both nodes add HADR provider hook script SAPHanaSR to HANA's global.ini. Do not copy the global.ini
file between nodes. Before editing global.ini, stop the HANA on both nodes. See manual page SAPHanaSR.py(7)
for details.
---

**Comment by lpinne** [comment]
the guide now highlights a procedure which says three time "Implement the python hook script ... on both sites."

thanks for reporting!
