### ISSUE TITLE
[doc] Example&nbsp;11:  Stop SAP HANA 

### ISSUE THREAD

**Issue by roseswe** [SUSE/suse-best-practices#96]
Example&nbsp;11:  Stop SAP HANA :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-1.9.6.5

How can we verify that the hook is working correctly?

**Comment by chabowski** [comment]
@fmherschel @lpinne @pirat013 
Ralph Roth has submitted several issues/questions  (via the "report a bug" link in the doc which opens a GitHub issue).
Can you please have a look? This is his third question/issue.
Thanks very much!

**Comment by fmherschel** [comment]
@rosewe: Good Point! I hope we can add the hook validation in the next version of the paper. As far as I remember we did add this info already to the next version of the cost optimized best practice. Once this doc is published we are working on the "backport" of the new findings to the perf optimized guide.
Thanks for the heads-up. This issue should be stay open till we could solve that.

**Comment by lpinne** [comment]
@rosewe: Thank your for the hint.
Next version will contain something like:
 * Example for checking the system log for srHook  setting  HANA  system
       replication status in the CIB properties section.
         # grep "sudo.*crm_attribute.*srHook" /var/log/messages

 *  Example  for  checking the HANA tracefiles for srConnectionChanged()
       events.
         # su - sleadm
         ~> cdtrace
         ~> grep SAPHanaSR.srConnectionChanged.*called nameserver_*.trc
         ~> grep crm_attribute.*SAPHanaSR nameserver_*.trc
         # exit

**Comment by lpinne** [comment]
the guide now contains examples fro checking all three hook scripts.

thanks for reporting!
