### ISSUE TITLE
[doc] Example&nbsp;7:  Copy the KEY and KEY-DATA file from the primary to the secondary site 

### ISSUE THREAD

**Issue by roseswe** [SUSE/suse-best-practices#97]
Example&nbsp;7:  Copy the KEY and KEY-DATA file from the primary to the secondary site :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-1.8.8.4

This rsync example needs an overhaul, or should be replaced e.g. by scp or completely left of. In the current way it confuses the reader more than being helpful.

**Comment by chabowski** [comment]
@fmherschel @lpinne @pirat013 
Ralph Roth has submitted several issues/questions  (via the "report a bug" link in the doc which opens a GitHub issue).
Can you please have a look? This is his fourth question/issue.
Thanks very much!

**Comment by fmherschel** [comment]
@rosewe: Could you explain why scp would be better than rsync?

**Comment by lpinne** [comment]
@roseswe: Thanks for the comments. May I ask to better understand:
1. What is the advantage of scp over rsync?
2. How should the cluster work without syncing the files?
3. What would be a better explanation?

**Comment by chabowski** [comment]
Hi @roseswe have you seen the questions above from Lars?
Would be great if you could have a look and answer, so that in a next version, this might be enhanced.

@lpinne @fmherschel please let me know if/when to close this issue. 
Thank you!!

**Comment by lpinne** [comment]
since no answer an no one else complained during two years, we might close this
